"use client";

import Link from "next/link";
import { BarChart3, Bell, RefreshCw, Send, ShieldCheck, Tag } from "lucide-react";
import { useI18n } from "@/lib/i18n";

const options = [["automation.simple.weeklyReport", "automation.simple.weeklyReportDesc", BarChart3], ["automation.simple.decliningAlert", "automation.simple.decliningAlertDesc", Bell], ["automation.simple.monitoring", "automation.simple.monitoringDesc", ShieldCheck], ["automation.simple.plannedReminder", "automation.simple.plannedReminderDesc", Tag], ["automation.simple.watchlist", "automation.simple.watchlistDesc", RefreshCw]] as const;

export default function AutomationPage() {
  const { t } = useI18n();
  return <main className="min-h-screen px-4 pb-12 pt-6 sm:px-6 lg:px-8 lg:pt-8"><div className="mx-auto max-w-[1120px]"><header className="border-b border-charcoal/[0.08] pb-6"><h1 className="text-3xl font-semibold tracking-[-0.05em] text-charcoal">{t("automation.title")}</h1><p className="mt-2 max-w-xl text-[12px] leading-5 text-charcoal/55">{t("automation.subtitle")}</p></header><section className="mt-6"><h2 className="text-[18px] font-semibold text-charcoal">{t("automation.recommended")}</h2><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{options.map(([title, description, Icon]) => <article key={title} className="rounded-[14px] border border-charcoal/[0.07] bg-white p-4"><Icon size={17} className="text-terracotta"/><h3 className="mt-3 text-[15px] font-semibold text-charcoal">{t(title)}</h3><p className="mt-1.5 text-[12px] leading-5 text-charcoal/55">{t(description)}</p><button type="button" disabled className="mt-3 h-8 rounded-[9px] border border-charcoal/[0.1] px-3 text-[11px] font-semibold text-charcoal/40">{t("automation.unavailable")}</button></article>)}</div></section><section className="mt-6 rounded-[14px] border border-charcoal/[0.07] bg-white p-4"><h2 className="text-[17px] font-semibold text-charcoal">{t("automation.mine")}</h2><p className="mt-3 rounded-[11px] bg-[#FCFAF8] p-4 text-[12px] text-charcoal/50">{t("automation.empty")}</p></section><section className="mt-6 rounded-[14px] border border-charcoal/[0.07] bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Send size={17} className="text-terracotta"/><div><h2 className="text-[16px] font-semibold text-charcoal">{t("automation.telegram")}</h2><p className="mt-1 text-[12px] text-charcoal/50">{t("automation.telegramUnavailable")}</p></div></div><Link href="/connections" className="inline-flex h-8 items-center rounded-[9px] border border-charcoal/[0.1] px-3 text-[11px] font-semibold text-charcoal/65">{t("automation.connections")}</Link></div></section></div></main>;
}
