import uk from "./uk";

const enOverrides: Record<string, string> = {
  "nav.home": "Home",
  "nav.chat": "Chat with Lucy",
  "nav.analytics": "Analytics",
  "nav.listings": "Listings",
  "nav.policies": "Shop Policies",
  "nav.research": "Research",
  "nav.automation": "Automation",
  "nav.reports": "Reports",
  "nav.connections": "Connections",
  "nav.subscription": "Subscription",
  "nav.billing": "Subscription",
  "nav.settings": "Settings",

  "plan.label": "PLAN",
  "plan.month": "month",
  "connections.status.loading": "Loading",
  "connections.status.unavailable": "Backend unavailable",
  "connections.status.unauthenticated": "Sign in required",
  "connections.status.notConnected": "Not connected",
  "connections.status.requestFailed": "The request could not be completed.",
  "connections.confirmDisconnect.title": "Disconnect Etsy?",
  "connections.confirmDisconnect.body": "This will stop synchronization and related automations.",
  "connections.feature.Listings": "Listings",
  "connections.feature.Reports": "Reports",
  "settings.ai.concise": "Concise", "settings.ai.balanced": "Balanced", "settings.ai.detailed": "Detailed", "settings.ai.professional": "Professional", "settings.ai.friendly": "Friendly", "settings.ai.direct": "Direct", "settings.language.ukrainian": "Ukrainian", "settings.language.english": "English",
  "plan.storeUsage": "1 of 1 stores",
  "plan.manageSubscription": "Manage Subscription",
  "settings.title": "Settings", "settings.subtitle": "Manage your profile, shop, AI models, notifications, and Lucy Seller Copilot behavior.", "settings.interfaceLanguage": "Interface Language", "settings.saved": "Changes Saved", "settings.name": "Name", "settings.company": "Company / Agency Name", "settings.timezone": "Timezone", "settings.avatar": "Avatar", "settings.avatarHint": "PNG or JPG, up to 5 MB", "settings.changePhoto": "Change Photo", "settings.role": "ROLE", "settings.plan": "PLAN", "settings.stores": "STORES", "settings.month": "month", "settings.storeUsage": "1 / 1", "settings.tab.profile": "Profile", "settings.tab.shop": "Shop", "settings.tab.ai": "AI & Lucy", "settings.tab.notifications": "Notifications", "settings.tab.reports": "Reports", "settings.tab.language": "Language & Region", "settings.tab.security": "Security", "settings.tab.legal": "Legal", "settings.profile.title": "Profile", "settings.profile.subtitle": "Basic account information", "settings.workspace.title": "Your Workspace", "settings.workspace.subtitle": "Current access profile", "settings.shop.title": "Shop Settings", "settings.shop.subtitle": "Basic Etsy shop settings", "settings.shop.name": "Shop Name", "settings.shop.marketplace": "Default Marketplace", "settings.shop.default": "Default Shop", "settings.shop.sync": "Sync Now", "settings.shop.connections": "Go to Connections", "settings.currency": "Currency", "settings.ai.title": "AI & Lucy", "settings.ai.subtitle": "Configure your assistant's working style", "settings.ai.defaultModel": "Default AI Model", "settings.ai.preferredUse": "Preferred Use", "settings.ai.autoSelect": "Automatically Select Model", "settings.ai.responseStyle": "Response Style", "settings.ai.tone": "Lucy Tone", "settings.behavior.title": "Lucy Behavior", "settings.behavior.subtitle": "Manage suggestions and confirmations", "settings.behavior.recommendations": "Show Recommendations", "settings.behavior.insights": "Show AI Insights", "settings.behavior.seo": "Automatically Suggest SEO Improvements", "settings.behavior.confirm": "Confirm Important Changes", "settings.behavior.explanations": "Show Explanations for Actions", "settings.behavior.notice": "Confirmation before publishing and other important actions is enabled.", "settings.notifications.title": "Notifications", "settings.notifications.channels": "Delivery Channels", "settings.notifications.inApp": "In-App Notifications", "settings.notifications.telegram": "Telegram", "settings.notifications.email": "Email", "settings.notifications.types": "Notification Types", "settings.notifications.typesSubtitle": "Choose the events you want to know about", "settings.notifications.weeklyReady": "Weekly Report Ready", "settings.notifications.dailyReady": "Daily Report Ready", "settings.notifications.automationFailed": "Automation Failed", "settings.notifications.etsyIssue": "Etsy Connection Issue", "settings.notifications.lowConversion": "Low Conversion Alert", "settings.notifications.seoOpportunity": "SEO Opportunity", "settings.notifications.taskCompleted": "Scheduled Task Completed", "settings.saveSettings": "Save Settings", "settings.reports.title": "Report Settings", "settings.reports.subtitle": "Standard shop reports", "settings.report.daily": "Daily Report", "settings.report.weekly": "Weekly Report", "settings.report.financial": "Financial Report", "settings.reports.deliveryTime": "Delivery Time", "settings.reports.weeklySchedule": "Weekly Schedule", "settings.reports.channels": "Report Channels", "settings.reports.channelsSubtitle": "Available delivery methods", "settings.reports.channel.inApp": "In App", "settings.reports.channel.telegram": "Telegram", "settings.reports.channel.emailLater": "Email (later)", "settings.language.title": "Language & Region", "settings.language.subtitle": "Interface and data formats", "settings.dateFormat": "Date Format", "settings.security.title": "Security", "settings.security.subtitle": "Account security status", "settings.security.password": "Password / Authentication", "settings.security.passwordValue": "Protected", "settings.security.sessions": "Active Sessions", "settings.security.sessionsValue": "1 active session", "settings.security.services": "Connected Services", "settings.security.servicesValue": "4 services", "settings.security.lastSignIn": "Last Sign-In", "settings.security.lastSignInValue": "Today, 8:42 AM", "settings.security.oauth": "Etsy Connection", "settings.security.oauthValue": "3 active", "settings.security.signOut": "Sign Out of All Devices", "settings.security.viewConnections": "View Connections", "settings.privacy.title": "Data & Privacy", "settings.privacy.subtitle": "Manage your data", "settings.privacy.export": "Export My Data", "settings.privacy.clearChat": "Clear Chat History", "settings.privacy.delete": "Delete Account", "settings.confirm.title": "Confirm Action", "settings.confirm.body": "This action cannot be undone.", "settings.confirm.confirm": "Confirm", "settings.notice.photo": "Photo picker opened", "settings.notice.sync": "Synchronization started", "settings.notice.connections": "Going to Connections", "settings.notice.export": "Data export prepared", "settings.notice.confirmed": "Action available after API connection",

  "common.store": "Main Etsy shop",
  "common.catalog": "Catalog",
  "common.lucyTools": "Lucy Tools",
  "common.unavailable": "Unavailable",
  "common.refresh": "Refresh",
  "etsy.unavailableNote": "Not available from the current Etsy API connection",
  "etsy.createDraft": "Create Etsy Draft",
  "etsy.draftOnlyNote": "Lucy creates a draft only. You publish the final listing manually in Etsy.",
  "etsy.productType": "Product type",
  "etsy.productType.physical": "Physical",
  "etsy.productType.digital": "Digital",
  "etsy.whoMade": "Who made it?",
  "etsy.whoMade.iDid": "I made it",
  "etsy.whoMade.someoneElse": "Someone else",
  "etsy.whoMade.collective": "A member of my shop / collective",
  "etsy.whenMade": "When was it made?",
  "etsy.shippingProfile": "Shipping profile",
  "etsy.readinessProfile": "Processing profile",
  "etsy.select": "Select",
  "etsy.loading": "Loading...",
  "etsy.noListings": "No listings found",
  "etsy.loadError": "Could not load Etsy data",
  "common.searchTools": "Search tools...",
  "common.askLucy": "Ask Lucy",
  "common.needTool": "Need another tool?",
  "common.connected": "Connected",
  "billing.currentPlanButton": "Current Plan",
  "common.ready": "Ready",
  "common.active": "Active",
  "common.save": "Save changes",
  "common.cancel": "Cancel",
  "common.create": "Create",
  "common.check": "Check",
  "common.configure": "Configure",
  "common.reconnect": "Reconnect",
  "common.sync": "Sync now",
  "chat.title": "Chat with Lucy",
  "chat.subtitle": "Ask Lucy about your shop, listings, SEO, and analytics",
  "chat.new": "New chat",
  "chat.shopSelector": "Shop selector",
  "chat.shop.primary": "Main Etsy shop",
  "chat.shop.secondary": "Shop 2",
  "chat.history.0": "Store SEO analysis",
  "chat.history.1": "Competitor analysis",
  "chat.history.2": "New listing",
  "chat.history.3": "Keywords",
  "chat.history.4": "Weekly report",
  "chat.demoPrompt": "Analyze my weakest listings and tell me what needs improvement.",
  "chat.lucy": "Lucy",
  "chat.demoReply": "I found 3 listings with low views and weak conversion.",
  "chat.weakSeo": "weak SEO title",
  "chat.fewTags": "too few relevant tags",
  "chat.lowPhotoCtr": "low CTR on the main photo",
  "chat.improveSeo": "Improve SEO",
  "chat.createDraft": "Create draft",
  "chat.prompt.0": "Analyze the shop",
  "chat.prompt.1": "Create a draft",
  "chat.prompt.2": "Find competitors",
  "chat.prompt.3": "Improve SEO",
  "chat.prompt.4": "Create a report",
  "chat.placeholder": "Ask Lucy...",
  "chat.attach": "Add attachment",
  "chat.send": "Send message",
  "chat.disclaimer": "Lucy may make mistakes. Please review important changes before publishing.",
  "home.welcome": "Welcome, Nataliia! 👋",
  "home.subtitle": "Here is what is happening in your shop today.",
  "home.notifications": "Notifications",
  "home.storePicker": "Shop selector",
  "home.store.primary": "Main Etsy shop",
  "home.store.secondary": "Shop 2",
  "home.hero.badge": "AI ASSISTANT",
  "home.hero.badgeSecondary": "Always here",
  "home.hero.greeting": "Hi! I’m",
  "home.hero.name": "Lucy",
  "home.hero.subtitle": "I’m your AI assistant for Etsy. Ask me about your shop, listings, SEO, competitors, and analytics.",
  "home.hero.cta": "Start chat",
  "home.hero.secondary": "Example prompts",
  "home.connected.title": "Connected accounts",
  "home.connected.subtitle": "Your workspace",
  "home.connected.active": "3 active",
  "home.stats.title": "Active listings",
  "home.stats.views": "Views",
  "home.stats.orders": "Orders",
  "home.stats.revenue": "Revenue",
  "home.quickActions.title": "QUICK ACTIONS",
  "home.quickActions.subtitle": "Common tasks",
  "home.quickActions.all": "All tools →",
  "home.quickActions.createListing": "Create draft",
  "home.quickActions.createListingDesc": "Prepare a new product draft for Etsy",
  "home.quickActions.competitorResearch": "Competitor analysis",
  "home.quickActions.competitorResearchDesc": "Market and niche research",
  "home.quickActions.viewAnalytics": "View analytics",
  "home.quickActions.viewAnalyticsDesc": "Current KPIs and trends",
  "home.quickActions.improveSeo": "Improve SEO",
  "home.quickActions.improveSeoDesc": "Titles, tags, and descriptions",
  "home.quickActions.weeklyReport": "Weekly report",
  "home.quickActions.weeklyReportDesc": "Performance summary",
  "home.activity.title": "RECENT ACTIVITY",
  "home.activity.subtitle": "Recent actions",
  "home.activity.live": "Live",
  "home.activity.storeUpdate": "Shop update",
  "home.activity.updatedListing": "Updated listing “Handmade Ceramic Mug”",
  "home.activity.seoAnalysis": "SEO analysis completed for 12 listings",
  "home.activity.publishedListing": "Created draft “Boho Wall Decor”",
  "home.activity.reportReady": "Weekly report is ready",
  "home.askLucy.title": "QUESTIONS FOR LUCY",
  "home.askLucy.subtitle": "Ask Lucy",
  "home.askLucy.prompt.0": "How can I improve conversion?",
  "home.askLucy.prompt.1": "Find profitable keywords",
  "home.askLucy.prompt.2": "Analyze competitors",
  "home.askLucy.placeholder": "Write a question...",
  "home.askLucy.helper": "Lucy can help",
  "home.askLucy.send": "Send",
  "home.askLucy.status": "Shop update",

  "language.uk": "Ukrainian",
  "language.en": "English",
  "language.ua": "UA",
  "language.enShort": "EN",
  "language.title": "Language & Region",

  "sidebar.planLabel": "Plan",
  "sidebar.manageSubscription": "Manage Subscription",
  "sidebar.legal": "Legal",

  "policies.eyebrow": "LUCY SELLER COPILOT",
  "policies.title": "Shop Policies",
  "policies.subtitle": "Set up delivery, returns, and customer service rules for your Etsy shop.",
  "policies.save": "Save Policies",
  "policies.saved": "Policies saved",
  "policies.connected": "Connected",
  "policies.shipping.title": "Shipping",
  "policies.shipping.desc": "Processing time: 1–3 business days",
  "policies.returns.title": "Returns & Exchanges",
  "policies.returns.desc": "Buyers can contact us within 14 days",
  "policies.customOrders.title": "Custom Orders",
  "policies.customOrders.desc": "Discuss details before confirming an order",
  "policies.communication.title": "Buyer Communication",
  "policies.communication.desc": "We reply to messages within 1–2 business days",
  "policies.info.title": "Shop policies help set clear expectations for buyers.",
  "policies.info.desc": "Make sure your policies match your current processes and Etsy requirements.",

  "tool.catalog": "Catalog",
  "tool.lucyTools": "Lucy Tools",
  "tool.searchPlaceholder": "Search tools...",
  "tool.searchResults": "results",
  "tool.totalTools": "tools",
  "tool.emptyState": "Nothing found",
  "tool.emptyStateHint": "Try another search or section.",
  "tool.expand": "Expand Lucy tools",
  "tool.collapse": "Collapse Lucy tools",
  "tool.close": "Close panel",
  "tool.clearSearch": "Clear search",
  "tool.needOther": "Need another tool?",
  "tool.askLucy": "Ask Lucy",

  "tool.group.listings": "LISTINGS",
  "tool.group.research": "RESEARCH",
  "tool.group.seo": "SEO",
  "tool.group.analytics": "ANALYTICS",
  "tool.group.automation": "AUTOMATION",
  "tool.group.integrations": "INTEGRATIONS",

  "tool.listing.create": "Create draft",
  "tool.listing.createDesc": "Create a product draft with keywords",
  "tool.listing.drafts": "My drafts",
  "tool.listing.draftsDesc": "Review saved products",
  "tool.listing.update": "Edit draft",
  "tool.listing.updateDesc": "SEO and visual updates for a draft",
  "tool.listing.bulk": "Bulk creation",
  "tool.listing.bulkDesc": "Create multiple listings at once",
  "tool.listing.upload": "Upload photos",
  "tool.listing.uploadDesc": "Review and optimize media",

  "tool.research.competitors": "Competitor Analysis",
  "tool.research.competitorsDesc": "Track pricing and listing patterns",
  "tool.research.keywords": "Keyword Research",
  "tool.research.keywordsDesc": "Find stronger search phrases",
  "tool.research.niche": "Niche Analysis",
  "tool.research.nicheDesc": "Evaluate demand and competition",

  "tool.seo.analysis": "SEO Analysis",
  "tool.seo.analysisDesc": "Check title and tags",
  "tool.seo.titles": "Title Generator",
  "tool.seo.titlesDesc": "Create clear, strong titles",
  "tool.seo.descriptions": "Description Generator",
  "tool.seo.descriptionsDesc": "Improve product description",

  "tool.analytics.daily": "Daily Report",
  "tool.analytics.dailyDesc": "Key changes for the day",
  "tool.analytics.weekly": "Weekly Report",
  "tool.analytics.weeklyDesc": "Performance summary",
  "tool.analytics.revenue": "Revenue Report",
  "tool.analytics.revenueDesc": "Compare trends and profit",

  "tool.automation.queue": "Queue",
  "tool.automation.queueDesc": "Automate product tasks",
  "tool.automation.rules": "Rules",
  "tool.automation.rulesDesc": "Set workflow logic",
  "tool.automation.schedule": "Schedule",
  "tool.automation.scheduleDesc": "Schedule actions",

  "tool.integrations.etsy": "Etsy",
  "tool.integrations.etsyDesc": "Connected shop status",
  "tool.integrations.chatgpt": "ChatGPT",
  "tool.integrations.chatgptDesc": "AI model access",
  "tool.integrations.claude": "Claude",
  "tool.integrations.claudeDesc": "AI generation options",
  "tool.integrations.telegram": "Telegram",
  "tool.integrations.telegramDesc": "Notifications and updates",

  "topbar.search": "Search",
  "topbar.searchPlaceholder": "Search listings, keywords, shops...",
  "topbar.openNavigation": "Open navigation",
  "topbar.openTools": "Open Lucy tools",

  "analytics.title": "Analytics",
  "analytics.subtitle": "A complete view of your Etsy shop performance",
  "analytics.period.label": "Analytics period",
  "analytics.period.7d": "Last 7 days",
  "analytics.period.30d": "Last 30 days",
  "analytics.period.90d": "Last 90 days",
  "analytics.period.year": "This year",
  "analytics.kpi.revenue": "Revenue",
  "analytics.kpi.orders": "Orders",
  "analytics.kpi.views": "Views",
  "analytics.kpi.conversion": "Conversion",
  "analytics.salesRevenue": "Sales & Revenue",
  "analytics.salesRevenueSubtitle": "Shop performance over the selected period",
  "analytics.chartLabel": "Revenue and orders chart",
  "analytics.tooltip.revenue": "revenue",
  "analytics.aiInsights": "AI Insights",
  "analytics.aiInsightsSubtitle": "What Lucy sees in your data",
  "analytics.insight.conversion": "Conversion increased by 0.6% after the SEO update.",
  "analytics.insight.revenue": "3 listings generate 47% of total revenue.",
  "analytics.insight.mobile": "Mobile views increased by 21%.",
  "analytics.insight.lowConversion": "5 listings have low conversion.",
  "analytics.runFullAnalysis": "Run Full Analysis",
  "analytics.topListings": "Top Listings",
  "analytics.topListingsSubtitle": "Key performance metrics for your listings",
  "analytics.viewAll": "View All →",
  "analytics.listing": "Listing",
  "analytics.trend": "Trend",
  "analytics.trafficSources": "Traffic Sources",
  "analytics.trafficSourcesSubtitle": "Where your buyers come from",
  "analytics.salesFunnel": "Sales Funnel",
  "analytics.salesFunnelSubtitle": "The path from view to order",
  "analytics.funnel.views": "Views",
  "analytics.funnel.visits": "Visits",
  "analytics.funnel.cart": "Add to Cart",
  "analytics.funnel.orders": "Orders",
  "analytics.shopSEO": "Shop SEO Health",
  "analytics.shopSEOSubtitle": "Listing health and search visibility",
  "analytics.strongListings": "Strong listings",
  "analytics.needOptimization": "Need Optimization",
  "analytics.missingTags": "Missing tags",
  "analytics.improveSEO": "Improve SEO",

  "listings.header.title": "Listings",
  "listings.header.subtitle": "Manage your products, SEO, and publishing in one place.",
  "listings.header.createNotice": "New listing created.",
  "listings.header.create": "Create listing",
  "listings.header.syncNotice": "Sync is running.",
  "listings.header.importSync": "Import & sync",
  "listings.summary.aria": "Listings summary",
  "listings.summary.active": "Active",
  "listings.summary.drafts": "Drafts",
  "listings.summary.scheduled": "Scheduled",
  "listings.summary.needsSeo": "Needs SEO",
  "listings.categories.ceramics": "Ceramics",
  "listings.categories.jewelry": "Jewelry",
  "listings.categories.decor": "Decor",
  "listings.categories.templates": "Templates",
  "listings.categories.digital": "Digital Products",
  "listings.recommendations.title": "Recommendations",
  "listings.recommendations.subtitle": "What to update today",
  "listings.recommendations.openNotice": "Recommendations opened.",
  "listings.recommendations.viewAll": "View all",
  "listings.recommendations.lowSeo": "listings with weak SEO",
  "listings.recommendations.lowConversion": "listings with low conversion",
  "listings.recommendations.readyDrafts": "drafts ready to publish",
  "listings.recommendations.stale": "stale listings needing an update",
  "listings.search.placeholder": "Search listings...",
  "listings.filters.aria": "Listing filters",
  "listings.filters.category": "Category",
  "listings.filters.seoStatus": "SEO status",
  "listings.filters.below60": "Below 60",
  "listings.filters.60to79": "60–79",
  "listings.filters.80plus": "80+",
  "listings.filters.sales": "Sales",
  "listings.filters.salesNotice": "Sorted by sales.",
  "listings.filters.lastUpdated": "Last updated",
  "listings.filters.lastUpdatedNotice": "Sorted by update date.",
  "listings.filters.store": "Shop",
  "listings.filters.highestSeo": "Highest SEO",
  "listings.filters.mostSales": "Most sales",
  "listings.tabs.aria": "Listing tabs",
  "listings.tabs.all": "All",
  "listings.tabs.active": "Active",
  "listings.tabs.drafts": "Drafts",
  "listings.tabs.scheduled": "Scheduled",
  "listings.tabs.archived": "Archive",
  "listings.tabs.needsAttention": "Needs attention",
  "listings.status.active": "Active",
  "listings.status.draft": "Draft",
  "listings.status.scheduled": "Scheduled",
  "listings.status.archived": "Archived",
  "listings.view.table": "Table",
  "listings.view.cards": "Cards",
  "listings.bulk.selected": "Selected",
  "listings.bulk.apiReady": "Action is ready.",
  "listings.bulk.improveSeo": "Improve SEO",
  "listings.bulk.update": "Update",
  "listings.bulk.schedulePublishing": "Schedule publishing",
  "listings.bulk.archive": "Archive",
  "listings.table.selectAll": "Select all",
  "listings.table.selectItem": "Select",
  "listings.table.product": "Listing",
  "listings.table.status": "Status",
  "listings.table.seo": "SEO",
  "listings.table.views": "Views",
  "listings.table.orders": "Orders",
  "listings.table.conversion": "Conversion",
  "listings.table.revenue": "Revenue",
  "listings.table.updated": "Updated",
  "listings.actions.menu": "Actions for",
  "listings.actions.edit": "Edit",
  "listings.actions.view": "View",
  "listings.actions.improveSeo": "Improve SEO",
  "listings.actions.duplicate": "Duplicate",
  "listings.actions.schedule": "Schedule",
  "listings.actions.updatePhotos": "Update photos",
  "listings.actions.archive": "Archive",
  "listings.actions.delete": "Delete",
  "listings.empty.title": "No listings found",
  "listings.empty.subtitle": "Try adjusting the filters or creating a new listing.",
  "listings.empty.create": "Create listing",

  "research.header.title": "Research",
  "research.header.subtitle": "Research niches, competitors, keywords, and market opportunities",
  "research.header.new": "New Research",
  "research.header.newNotice": "New research ready to launch",
  "research.header.shop": "Main Etsy Shop",
  "research.tools.aria": "Research tools",
  "research.tools.start": "enter a query to start",
  "research.tools.competitorAnalysis": "Competitor Analysis",
  "research.tools.competitorAnalysisDesc": "Find strong competitors and compare their listings",
  "research.tools.keywordResearch": "Keyword Research",
  "research.tools.keywordResearchDesc": "Find strong Etsy search phrases",
  "research.tools.nicheAnalysis": "Niche Analysis",
  "research.tools.nicheAnalysisDesc": "Evaluate demand, competition, and niche potential",
  "research.tools.marketTrends": "Market Trends",
  "research.tools.marketTrendsDesc": "Track demand and market changes",
  "research.search.placeholder": "Enter a product, niche, keyword, or competitor URL...",
  "research.search.prompt": "Enter a query to research",
  "research.search.analyzing": "Researching",
  "research.search.cta": "Start Research",
  "research.search.try": "Try",
  "research.market.title": "Market Overview",
  "research.market.detail": "Current snapshot for the main shop niche",
  "research.market.demand": "Demand",
  "research.market.competition": "Competition",
  "research.market.averagePrice": "Average Price",
  "research.market.opportunity": "Opportunity",
  "research.market.high": "High",
  "research.market.medium": "Medium",
  "research.market.low": "Low",
  "research.market.growing": "Growing",
  "research.market.stable": "Stable",
  "research.market.declining": "Declining",
  "research.opportunities.title": "Niche Opportunities",
  "research.opportunities.detail": "Ideas with positive demand momentum",
  "research.opportunities.competitionLabel": "Competition",
  "research.opportunities.open": "Opened research",
  "research.opportunities.research": "Research",
  "research.competitors.title": "Competitors",
  "research.competitors.detail": "Benchmarks for positioning your shop",
  "research.competitors.shop": "Shop",
  "research.competitors.sales": "Sales",
  "research.competitors.listings": "Listings",
  "research.competitors.price": "Price",
  "research.competitors.rating": "Rating",
  "research.competitors.strength": "Strongest angle",
  "research.competitors.strength.visuals": "Strong visuals",
  "research.competitors.strength.gifts": "Gift sets",
  "research.competitors.strength.personalization": "Personalization",
  "research.competitors.strength.templates": "Digital templates",
  "research.competitors.actions": "Actions",
  "research.competitors.analyze": "Analyze",
  "research.keywords.title": "Keywords",
  "research.keywords.detail": "Demand, competition, and SEO guidance",
  "research.keywords.keyword": "Keyword",
  "research.keywords.demand": "Demand",
  "research.keywords.competition": "Competition",
  "research.keywords.trend": "Trend",
  "research.keywords.score": "Score",
  "research.keywords.score.strong": "Strong",
  "research.keywords.score.high-competition": "High competition",
  "research.keywords.score.medium": "Medium",
  "research.chart.title": "Demand Trend",
  "research.chart.detail": "Demand over the selected period",
  "research.chart.keywordLabel": "Keyword",
  "research.chart.periodLabel": "Demand for",
  "research.chart.legend.demand": "Demand",
  "research.chart.legend.category": "Category",
  "research.period.30d": "Last 30 days",
  "research.period.90d": "Last 90 days",
  "research.period.12m": "12 months",
  "research.insights.title": "What Lucy Sees",
  "research.insights.detail": "AI insights for the next step",
  "research.insights.recommendations": "Lucy Recommendations",
  "research.insights.item1": "Demand in this niche increased by 27% over the last 30 days.",
  "research.insights.item2": "The strongest price range is $28–42.",
  "research.insights.item3": "Competitors are underusing long-tail keywords.",
  "research.insights.item4": "There is room to create 3–5 new listings.",
  "research.insights.actionNotice": "Deep analysis launched",
  "research.insights.cta": "Generate Strategy",
  "research.saved.title": "Saved Research",
  "research.saved.subtitle": "Your recent working sessions",
  "research.saved.open": "Open",
  "research.saved.type.niche": "Niche analysis",
  "research.saved.type.keywords": "Keyword research",
  "research.saved.type.trends": "Market trends",
  "research.saved.type.competitors": "Competitors",
  "research.saved.created": "Created",
  "research.empty.title": "No research found",
  "research.empty.subtitle": "Create a new research project to see results here.",
  "research.empty.button": "New Research",

  "automation.header.title": "Automation",
  "automation.header.subtitle": "Automate your daily Etsy operations without losing visibility into the process.",
  "automation.header.newNotice": "New automation ready to launch.",
  "automation.header.create": "Create automation",
  "automation.store.main": "Main Etsy shop",
  "automation.summary.aria": "Automation summary",
  "automation.summary.activeRules": "Active rules",
  "automation.summary.inQueue": "In queue",
  "automation.summary.scheduled": "Scheduled",
  "automation.summary.completed30d": "Completed in 30 days",
  "automation.tabs.aria": "Automation tabs",
  "automation.tabs.rules": "Rules",
  "automation.tabs.queue": "Queue",
  "automation.tabs.schedule": "Schedule",
  "automation.tabs.history": "History",
  "automation.rules.title": "Rules",
  "automation.rules.subtitle": "Keep repetitive tasks on schedule and in sync with your store.",
  "automation.rules.newNotice": "New rule added.",
  "automation.rules.add": "Add rule",
  "automation.columns.trigger": "Trigger",
  "automation.columns.action": "Action",
  "automation.columns.lastRun": "Last run",
  "automation.columns.status": "Status",
  "automation.status.active": "Active",
  "automation.status.paused": "Paused",
  "automation.status.pending": "Pending",
  "automation.status.running": "Running",
  "automation.status.completed": "Completed",
  "automation.status.failed": "Failed",
  "automation.actions.menu": "Actions for",
  "automation.actions.edit": "Edit",
  "automation.actions.pause": "Pause",
  "automation.actions.delete": "Delete",
  "automation.rules.seoRefresh": "SEO refresh",
  "automation.trigger.seoBelow60": "SEO below 60",
  "automation.action.createOptimizationRecommendations": "Create optimization recommendations",
  "automation.rules.weeklyShopReport": "Weekly shop report",
  "automation.trigger.everyMonday0900": "Every Monday at 09:00",
  "automation.action.generateTelegramReport": "Generate Telegram report",
  "automation.rules.draftPublishingQueue": "Draft publishing queue",
  "automation.trigger.scheduledDateTime": "Scheduled date & time",
  "automation.action.processDraftQueue": "Process draft queue",
  "automation.rules.lowConversionAlert": "Low conversion alert",
  "automation.trigger.conversionBelow1": "Conversion below 1%",
  "automation.action.createLucyInsight": "Create Lucy insight",
  "automation.rules.keywordOpportunityAlert": "Keyword opportunity alert",
  "automation.store.mainShort": "Shop",
  "automation.queue.title": "Queue",
  "automation.queue.subtitle": "Review scheduled tasks and actions in progress.",
  "automation.queue.runNow": "Run queue now",
  "automation.queue.columns.task": "Task",
  "automation.queue.columns.listing": "Listing",
  "automation.queue.columns.type": "Type",
  "automation.queue.columns.scheduled": "Scheduled",
  "automation.queue.columns.status": "Status",
  "automation.queue.columns.actions": "Actions",
  "automation.queue.task.createDraft": "Create draft",
  "automation.queue.task.updateSeo": "Update SEO",
  "automation.queue.task.uploadImage": "Upload images",
  "automation.queue.task.generateReport": "Generate report",
  "automation.queue.task.processDraftQueue": "Process draft queue",
  "automation.queue.type.publish": "Publish",
  "automation.queue.type.seo": "SEO",
  "automation.queue.type.content": "Content",
  "automation.queue.type.report": "Report",
  "automation.queue.preview": "Task preview",
  "automation.queue.view": "View",
  "automation.schedule.title": "Schedule",
  "automation.schedule.subtitle": "Plan the next actions for your shop.",
  "automation.schedule.publishListing": "Publish listing",
  "automation.schedule.seoAudit": "SEO audit",
  "automation.schedule.generateWeeklyReport": "Generate weekly report",
  "automation.schedule.keywordResearch": "Keyword research",
  "automation.schedule.today": "Today",
  "automation.schedule.yesterday": "Yesterday",
  "automation.schedule.tomorrow": "Tomorrow",
  "automation.schedule.thisWeek": "This week",
  "automation.schedule.rulePrefix": "Rule:",
  "automation.history.title": "History",
  "automation.history.subtitle": "Recent automation outcomes and system events.",
  "automation.history.columns.action": "Action",
  "automation.history.columns.time": "Time",
  "automation.history.columns.result": "Result",
  "automation.history.columns.duration": "Duration",
  "automation.history.columns.source": "Source",
  "automation.history.successful": "Successful",
  "automation.history.failed": "Failed",
  "automation.opportunities.title": "Automation opportunities",
  "automation.opportunities.subtitle": "Easy wins to scale your shop.",
  "automation.opportunities.item1": "Improve listing SEO before the next weekend rush.",
  "automation.opportunities.item2": "Automate recurring checks for competitor pricing shifts.",
  "automation.opportunities.item3": "Set up keyword refreshes for new product collections.",
  "automation.opportunities.item4": "Send weekly reports to Telegram without manual work.",
  "automation.opportunities.createNotice": "Workflow created.",
  "automation.opportunities.cta": "Create workflow",
  "automation.health.title": "Automation health",
  "automation.health.subtitle": "Current operating performance",
  "automation.health.activeRules": "Active rules",
  "automation.health.queueStatus": "Queue status",
  "automation.health.stable": "Stable",
  "automation.health.lastRun": "Last run",
  "automation.health.failedActions": "Failed actions",
  "automation.health.nextTask": "Next task",
  "settings.legal": "Legal",
  "settings.legalDescription": "Lucy Seller Copilot documents and policies",
  "settings.terms": "Terms of Service",
  "settings.privacy": "Privacy Policy",
  "reports.title": "Reports",
  "reports.subtitle": "Create, review, and send reports for your Etsy shop.",
  "reports.create": "Create Report",
  "reports.store": "Main Etsy Shop",
  "reports.nextValue": "Mon, 9:00 AM",
  "reports.last": "Last",
  "reports.notCreated": "Not created yet",
  "reports.date.today": "Today",
  "reports.date.yesterday": "Yesterday",
  "reports.connected": "Connected",
  "reports.deliveryLabel": "Delivery",
  "reports.nextDelivery": "Next Delivery",
  "reports.edit": "Edit",
  "reports.editing": "Editing",
  "reports.period": "Period",
  "reports.kpi.thisMonth": "Reports This Month",
  "reports.kpi.automated": "Automated",
  "reports.kpi.telegramSent": "Sent to Telegram",
  "reports.kpi.next": "Next Report",
  "reports.types.title": "Report Types",
  "reports.types.subtitle": "Create reports from ready-made templates",
  "reports.type.daily": "Daily Report",
  "reports.type.daily.desc": "Key shop metrics for the day",
  "reports.type.weekly": "Weekly Report",
  "reports.type.weekly.desc": "Sales, traffic, SEO, and weekly changes",
  "reports.type.financial": "Financial Report",
  "reports.type.financial.desc": "Revenue, orders, fees, and available financial metrics",
  "reports.type.custom": "Custom Report",
  "reports.type.custom.desc": "Choose the available metrics and reporting period",
  "reports.recent.title": "Recent Reports",
  "reports.recent.subtitle": "Your generated and delivered reports",
  "reports.table.name": "Name",
  "reports.table.type": "Type",
  "reports.table.period": "Period",
  "reports.table.store": "Store",
  "reports.table.created": "Created",
  "reports.table.delivery": "Delivery",
  "reports.table.status": "Status",
  "reports.table.actions": "Actions",
  "reports.delivery.telegram": "Telegram",
  "reports.delivery.none": "-",
  "reports.status.sent": "Sent",
  "reports.status.ready": "Ready",
  "reports.action.view": "View",
  "reports.action.download": "Download",
  "reports.action.sendTelegram": "Send to Telegram",
  "reports.action.generateAgain": "Generate Again",
  "reports.action.schedule": "Schedule",
  "reports.action.delete": "Delete",
  "reports.actions.open": "Open report actions",
  "reports.telegram.title": "Telegram Delivery",
  "reports.telegram.subtitle": "Automatic report delivery",
  "reports.telegram.test": "Send Test Report",
  "reports.telegram.configure": "Configure Delivery",
  "reports.scheduled.title": "Scheduled Reports",
  "reports.scheduled.subtitle": "Upcoming automatic deliveries",
  "reports.frequency.daily": "Daily",
  "reports.frequency.monday": "Every Monday",
  "reports.financial.title": "Financial Snapshot",
  "reports.financial.subtitle": "Current month",
  "reports.financial.revenue": "Revenue",
  "reports.financial.fees": "Fees",
  "reports.financial.netRevenue": "Net Revenue",
  "reports.financial.open": "Open Financial Report",
  "reports.insights.title": "Lucy Insights",
  "reports.insights.subtitle": "What to know this week",
  "reports.insights.revenueUp": "Revenue is up 14%",
  "reports.insights.topListings": "3 listings generated 47% of total revenue",
  "reports.insights.averageOrder": "Average order value is up 9%",
  "reports.insights.seoUpdates": "5 listings need SEO updates",
  "reports.insights.createFull": "Create Full Report",
  "reports.custom.title": "Create Custom Report",
  "reports.custom.subtitle": "Build your own set of metrics",
  "reports.custom.thisMonth": "This month",
  "reports.custom.last30": "Last 30 days",
  "reports.custom.none": "Do not send",
  "reports.custom.create": "Create Report",
  "reports.metric.revenue": "Revenue",
  "reports.metric.orders": "Orders",
  "reports.metric.views": "Views",
  "reports.metric.conversion": "Conversion",
  "reports.metric.listings": "Listings",
  "reports.metric.seo": "SEO",
  "reports.metric.fees": "Fees",
  "reports.metric.profit": "Profit",
  "reports.notice.new": "New report ready to configure",
  "reports.notice.creating": "Creating",
  "reports.notice.apiReady": "UI ready for API",
  "reports.notice.testSent": "Test report sent",
  "reports.notice.deliverySettings": "Delivery settings opened",
  "reports.notice.financialOpened": "Financial report opened",
  "reports.notice.fullReport": "Full report is being created",
  "reports.notice.customCreated": "Custom report created",

  "connections.title": "Connections", "connections.subtitle": "Manage shops, AI models, and services connected to Lucy Seller Copilot.", "connections.add": "Add Connection", "connections.connected": "Connected", "connections.mainShop": "Main Etsy Shop", "connections.lastCheck": "Last Check", "connections.checkConnection": "Check Connection", "connections.check": "Check", "connections.sync": "Sync Now", "connections.configure": "Configure", "connections.reconnect": "Reconnect", "connections.disconnect": "Disconnect", "connections.primary": "Primary", "connections.addShop": "Connect another shop", "connections.planLimit": "Plan limit: 1 shop", "connections.proPlan": "PRO PLAN", "connections.shopWord": "stores", "connections.synced": "Synced", "connections.kpi.active": "Active Connections", "connections.kpi.shops": "Etsy Shops", "connections.kpi.ai": "AI Services", "connections.kpi.lastSync": "Last Sync", "connections.services.title": "Connected Services", "connections.services.subtitle": "Services available in your workspace", "connections.service.etsyDesc": "Access to shop data, listings, reviews, and analytics.", "connections.service.chatgptDesc": "AI model for chat, SEO, analysis, and content generation.", "connections.service.claudeDesc": "AI model for analysis, generation, and advanced tasks.", "connections.service.telegramDesc": "Reports, notifications, and automated updates.", "connections.service.accountShop": "ACCOUNT / SHOP", "connections.service.accountModel": "ACCOUNT / MODEL", "connections.account.shop": "Main Etsy Shop", "connections.account.configured": "Model Configured", "connections.account.reports": "Lucy Seller Reports", "connections.feature.shopData": "Shop Data", "connections.feature.listings": "Listings", "connections.feature.reviews": "Reviews", "connections.feature.drafts": "Drafts", "connections.feature.listingUpdates": "Listing Updates", "connections.feature.images": "Images", "connections.feature.reports": "Reports", "connections.feature.oauth": "OAuth Active", "connections.feature.Chat": "Chat", "connections.feature.SEO": "SEO", "connections.feature.Analysis": "Analysis", "connections.feature.Notifications": "Notifications", "connections.feature.Automation": "Automation", "connections.health.title": "Connection Health", "connections.health.subtitle": "Secure OAuth and recent API check status", "connections.health.oauth": "OAuth", "connections.health.access": "Access", "connections.health.sync": "Sync", "connections.health.lastApi": "Last API Request", "connections.health.active": "Active", "connections.health.ready": "Ready", "connections.health.operational": "All Systems Operational", "connections.system.title": "System Status", "connections.system.subtitle": "Last successful check", "connections.shops.title": "Etsy Shops", "connections.activity.title": "Recent Activity", "connections.activity.subtitle": "Events from connected services", "connections.activity.etsySync": "Etsy sync completed", "connections.activity.telegramTest": "Telegram test report sent", "connections.activity.claudeCheck": "Claude connection checked", "connections.activity.etsyToken": "Etsy token refreshed", "connections.date.yesterday": "Yesterday", "connections.security.title": "Connection Security", "connections.security.subtitle": "Your data stays protected", "connections.security.body": "Lucy uses secure connections and does not display secret keys or tokens in your interface.", "connections.actions.open": "Open connection actions", "connections.action.makePrimary": "Make Primary", "connections.action.sync": "Synchronize", "connections.action.reconnect": "Reconnect", "connections.action.delete": "Delete Connection", "connections.notice.new": "New connection ready to configure", "connections.notice.checked": "connection checked", "connections.notice.configured": "configuration opened", "connections.notice.reconnected": "Connection reconnected", "connections.notice.disconnected": "Connection disconnected", "connections.notice.apiReady": "UI ready for API", "connections.notice.planLimit": "Plan limit: 1 shop",

  "billing.title": "Subscription", "billing.subtitle": "Manage your plan, billing, and store limits.", "billing.manageBilling": "Manage Billing", "billing.currentPlan": "CURRENT PLAN", "billing.active": "Active", "billing.month": "month", "billing.stores": "STORES", "billing.storeUsage": "1 of 1 stores", "billing.nextBilling": "NEXT BILLING", "billing.status": "STATUS", "billing.autoRenewEnabled": "Auto-renewal enabled", "billing.manageSubscription": "Manage Subscription", "billing.upgrade": "Upgrade to MULTI STORE", "billing.cancelSubscription": "Cancel Subscription", "billing.choosePlan": "Choose a Plan", "billing.choosePlanSubtitle": "Two plans for different shop needs", "billing.planBadge.pro": "Your Plan", "billing.planBadge.multi": "Best for Growth", "billing.plan.pro": "For one Etsy shop.", "billing.plan.multi": "For sellers and teams managing multiple Etsy shops.", "billing.feature.oneStore": "1 store", "billing.feature.upToFive": "Up to 5 stores", "billing.feature.ai": "ChatGPT + Claude", "billing.feature.listingAnalysis": "Listing Analysis", "billing.feature.keywordResearch": "Keyword Research", "billing.feature.drafts": "Draft Creation", "billing.feature.telegram": "Telegram Delivery", "billing.feature.allTools": "All Lucy Tools", "billing.feature.shopAnalysis": "Shop Analysis", "billing.feature.competitorAnalysis": "Competitor Analysis", "billing.feature.seo": "SEO Optimization", "billing.feature.reports": "Reports", "billing.feature.basicAutomation": "Basic Automation", "billing.feature.multiShopAnalysis": "Multi-Shop Analysis", "billing.feature.bulkCreation": "Bulk Creation", "billing.feature.reportsEachShop": "Reports for Each Shop", "billing.feature.prioritySupport": "Priority Support", "billing.feature.advancedAnalytics": "Advanced Analytics", "billing.feature.automation": "Automation", "billing.autoRenewNotice": "Your subscription renews automatically each month until you cancel it.", "billing.termsPrefix": "I have read and agree to the", "billing.terms": "Terms of Use", "billing.and": "and", "billing.privacy": "Privacy Policy", "billing.mainShop": "Main Etsy Shop", "billing.usage.title": "Usage", "billing.usage.subtitle": "Current store limit", "billing.usage.limitReached": "Plan limit reached", "billing.usage.connectedShop": "Connected shop:", "billing.details.title": "Subscription Details", "billing.details.subtitle": "Current terms of your plan", "billing.details.plan": "Plan", "billing.details.price": "Price", "billing.details.status": "Status", "billing.details.renewal": "Auto-renewal", "billing.details.nextBilling": "Next Billing", "billing.details.payment": "Payment Method", "billing.enabled": "Enabled", "billing.payment.title": "Billing", "billing.payment.subtitle": "Manage payment details through the secure portal", "billing.payment.protected": "Card details are protected by Stripe", "billing.managePayment": "Manage Payment Method", "billing.viewInvoices": "View Invoices", "billing.manage.title": "Manage Subscription", "billing.manage.subtitle": "Changes are made in Stripe Billing Portal", "billing.manage.body": "You can change or cancel your subscription through Stripe Billing Portal.", "billing.manage.cancelBody": "Cancellation stops future renewals, while the paid period generally remains available until it ends.", "billing.comparison.title": "Plan Comparison", "billing.comparison.subtitle": "A quick look at available features", "billing.comparison.feature": "Feature", "billing.comparison.row.stores": "Stores", "billing.comparison.row.ai": "ChatGPT + Claude", "billing.comparison.row.allTools": "All Tools", "billing.comparison.row.analytics": "Analytics", "billing.comparison.row.automation": "Automation", "billing.comparison.row.telegram": "Telegram Delivery", "billing.comparison.row.prioritySupport": "Priority Support", "billing.upToFive": "up to 5", "billing.basic": "Basic", "billing.advanced": "Advanced", "billing.history.title": "Billing History", "billing.history.subtitle": "Recent subscription charges", "billing.paymentStatus.paid": "Paid", "billing.invoice": "Invoice", "billing.refundPolicy": "Need a refund? Review the applicable policy.", "billing.refundLink": "Refund Policy", "billing.notice.portal": "Stripe Customer Portal will be available after connection", "billing.notice.subscription": "Subscription management opened", "billing.notice.upgrade": "Upgrade to MULTI STORE opened", "billing.notice.cancel": "Cancellation is available through Stripe Billing Portal", "billing.notice.current": "This is your current plan", "billing.notice.payment": "Payment method settings opened", "billing.notice.invoices": "Invoices opened", "billing.loading": "Loading subscription…", "billing.loadError": "Could not load billing status.", "billing.status.active": "Active", "billing.status.trialing": "Trial", "billing.status.past_due": "Payment past due", "billing.status.canceled": "Canceled", "billing.status.unpaid": "Unpaid", "billing.status.paused": "Paused", "billing.status.incomplete": "Incomplete", "billing.status.incomplete_expired": "Expired", "billing.status.cancelled": "Canceled", "billing.periodEndLabel": "Current period ends", "billing.lastPaymentLabel": "Last payment", "billing.noExpiration": "Not set", "billing.noPayment": "No payment recorded yet", "billing.noStripeAccount": "This account has no Stripe subscription attached — it was set up manually. Contact support to change billing.", "billing.noPortalConfigured": "Billing portal isn't configured yet. Contact support.", "billing.openPortal": "Open Stripe Billing Portal", "billing.autoRenewOff": "Auto-renewal is off — access ends after the current period.", "billing.willCancel": "Cancels at period end",

  "settings.subscription": "Subscription & Billing Policy",
  "settings.refund": "Refund & Cancellation Policy",
  "settings.cookies": "Cookie Policy",
  "settings.ai": "AI Disclaimer",
  "settings.acceptable": "Acceptable Use Policy",
  "settings.openDocument": "Open document",
  "settings.exportData": "Export my data",
  "settings.clearChat": "Clear chat history",
  "settings.requestCorrection": "Request data correction",
  "settings.deleteAccount": "Delete account",
  "settings.privacySupport": "Contact privacy support",
};

export const en = { ...uk, ...enOverrides };
export default en;
