export type LegalLocale = "uk" | "en";
export type LegalDocument = { title: string; updated: string; effective?: string; version?: string; sections: Array<readonly [string, string]> };

const providerUk = "Постачальник сервісу: ФОП Піцина Жанна Вікторівна, Україна, Рівне. Контактна адреса: 2 Klenova Street, Rivne, Ukraine. Підтримка: support@enjoyagency.com.ua.";
const providerEn = "Service provider: Sole Proprietor Zhanna Pitsyna, Ukraine, Rivne. Legal/contact address: 2 Klenova Street, Rivne, Ukraine. Support: support@enjoyagency.com.ua.";
const rightsUk = "Нічого в цих умовах не обмежує та не виключає обов’язкові права споживачів, від яких не можна законно відмовитися за правом, застосовним до клієнта. Для клієнтів за межами України обов’язкові правила захисту прав споживачів їхньої юрисдикції застосовуються, якщо цього вимагає закон.";
const rightsEn = "Nothing in these terms limits or excludes mandatory consumer rights that cannot legally be waived under the laws applicable to the customer. For customers outside Ukraine, mandatory consumer protection rules of their jurisdiction may still apply where required by law.";

const uk: Record<string, LegalDocument> = {
  terms: { title: "Умови використання", updated: "Оновлено: 28 серпня 2026", sections: [
    ["Постачальник", providerUk],
    ["Про Lucy Seller Copilot", "Lucy Seller Copilot — підписний SaaS/AI-сервіс для продавців Etsy. Він допомагає з аналізом магазину та лістингів, SEO-рекомендаціями, пошуком ключових слів і конкурентів, дослідженням ніші, створенням чернеток і оновленнями лістингів, роботою із зображеннями, звітами, автоматизацією, доставкою через Telegram та AI-чатом."],
    ["Правоздатність і вимоги", "Користувачі повинні мати правоздатність, необхідну для укладення цієї угоди за правом, що до них застосовується. Якщо користувач не досяг віку правоздатності у своїй юрисдикції, він може користуватися сервісом лише за участю та згодою батьків або законного опікуна, якщо це дозволено законом. Також потрібно відповідати вимогам сторонніх платформ, зокрема Etsy."],
    ["Відсутність гарантованих результатів", "Сервіс не гарантує продажі, позиції в Etsy, дохід, зростання конверсії, видимість, схвалення маркетплейсом або безпомилковість AI-виводу."],
    ["Відповідальність продавця", "Продавець відповідає за товари, лістинги, права інтелектуальної власності, дотримання правил маркетплейсів, ціни, податки, доставку, обслуговування клієнтів і фінальні рішення щодо публікації."],
    ["Сторонні сервіси", "Lucy може взаємодіяти з Etsy, OpenAI/ChatGPT, Anthropic/Claude, Telegram, платіжними провайдерами, хостингом, базами даних та email-провайдерами. Lucy є незалежним сервісом і не є Etsy та не підтримується Etsy, OpenAI, Anthropic, Telegram або іншою платформою."],
    ["Доступність Etsy", "Функції можуть змінюватися або ставати недоступними через зміни Etsy API, обмеження платформи, OAuth, збої, зміни політик або rate limits."],
    ["AI-вивід", "Тексти, SEO-рекомендації, аналіз і дослідження є інформаційною допомогою. Перевіряйте важливі зміни перед публікацією."],
    ["Облікові записи та безпека", "Користувач відповідає за облікові дані, авторизовані Etsy-підключення та активність у своєму акаунті."],
    ["Підписка", "PRO PLAN коштує $59 USD на місяць для 1 Etsy-магазину. MULTI STORE коштує $99 USD на місяць і підтримує до 5 Etsy-магазинів. Підписка оплачується щомісяця та автоматично поновлюється до скасування."],
    ["Призупинення і припинення", "Доступ може бути призупинений або припинений у разі шахрайства, незаконних дій, зловживань, загроз безпеці, порушення умов, обходу API/безпеки або несплати."],
    ["Інтелектуальна власність", "Інтерфейс, бренд, програмне забезпечення та власні матеріали Lucy належать постачальнику або відповідним ліцензіарам. Користувач зберігає права на завантажений контент, надаючи необхідні права для його обробки з метою роботи сервісу."],
    ["Обмеження відповідальності", "У межах, дозволених законом, постачальник не відповідає за непрямі збитки, втрату прибутку або рішення, прийняті на основі сервісу. Це обмеження не застосовується до відповідальності, яку закон не дозволяє обмежити."],
    ["Застосовне право", "До сервісу застосовується право України. " + rightsUk],
    ["Контакти", providerUk]
  ] },
  privacy: { title: "Політика конфіденційності", updated: "Оновлено: 28 серпня 2026", sections: [
    ["Контролер даних", providerUk],
    ["Дані облікового запису", "Ми можемо обробляти ім’я, email, дані автентифікації, назву компанії, країну/регіон, телефон за наявності, мову, часовий пояс і налаштування."],
    ["Дані підключеного Etsy-магазину", "Залежно від дозволів API можуть оброблятися інформація магазину, shop ID, лістинги, чернетки, зображення/відео лістингів, секції, відгуки, статистика магазину, замовлення та дані продажів, дохід/фінансові метрики, якщо вони доступні через авторизований API, і стан OAuth-підключення. Etsy Ads не підтримується та не заявляється."],
    ["AI та чат", "Можуть оброблятися промпти, повідомлення чату, текст лістингів, запити дослідження та дані магазину/лістингу, потрібні для відповіді на запит користувача."],
    ["Telegram", "Можуть оброблятися Telegram user/chat identifiers, потрібні для доставки, налаштування доставки та надіслані звіти чи сповіщення."],
    ["Підписка та білінг", "Можуть оброблятися статус підписки, план, billing/customer identifiers і статус платежу. Повні дані картки не зберігаються в інтерфейсі Lucy та обробляються платіжним провайдером, якщо застосовується."],
    ["Технічні дані", "Можуть оброблятися IP-адреса, браузер/пристрій, часові мітки, журнали безпеки й помилок та інформація про сесію."],
    ["Мета обробки", "Дані потрібні для надання Lucy, автентифікації, підключення Etsy, виконання запитаних операцій, AI-відповідей, звітів, Telegram-сповіщень, керування підписками, підтримки, безпеки, запобігання шахрайству/зловживанням, виконання юридичних обов’язків і підвищення надійності."],
    ["Правові підстави", "Залежно від обставин підставою може бути виконання договору, законний інтерес, згода, якщо вона потрібна, або виконання юридичного обов’язку. Підстава залежить від категорії даних і застосовної юрисдикції."],
    ["Постачальники та передачі", "Можуть використовуватися категорії AI-провайдерів, хостингу/cloud/database, платіжної обробки, transactional email, Telegram та Etsy API. До фактичного запуску конкретного провайдера ми не заявляємо, що він отримує production-дані. Провайдери можуть обробляти дані за межами України; застосовуються належні гарантії, якщо цього вимагає закон."],
    ["Зберігання", "Ми зберігаємо персональні дані стільки, скільки це обґрунтовано потрібно для надання сервісу, виконання юридичних обов’язків, вирішення спорів, виконання угод і безпеки. Точніші строки можуть бути опубліковані пізніше."],
    ["Безпека та права", "Ми застосовуємо технічні й організаційні заходи безпеки. Залежно від права ви можете мати право на доступ, виправлення, видалення, обмеження, заперечення, переносимість, відкликання згоди та скаргу компетентному наглядовому органу."],
    ["Запити та контакт", "Для запиту доступу, виправлення, видалення, експорту, корекції або privacy support зверніться на support@enjoyagency.com.ua. Не надсилайте API keys, access tokens, refresh tokens чи інші секрети."]
  ] },
  subscription: { title: "Умови підписки та оплати", updated: "Оновлено: 28 серпня 2026", sections: [
    ["Плани", "PRO PLAN — $59 USD/month, 1 Etsy store. MULTI STORE — $99 USD/month, до 5 Etsy stores. Річних, довічних планів і безкоштовного пробного періоду немає."],
    ["Початок і щомісячна оплата", "Підписка починається після успішної оплати/активації, оплата повторюється щомісяця, а підписка автоматично поновлюється, доки її не буде скасовано. Ціна та ліміт магазинів показуються до покупки."],
    ["Зміна плану", "Оновлення або зниження плану може впливати на майбутнє списання відповідно до підтвердження платіжного провайдера."],
    ["Невдалий платіж", "Невдалий платіж може призвести до призупинення платної функціональності. Користувач відповідає за актуальність платіжних даних."],
    ["Скасування і доступ", "Користувач може скасувати майбутні поновлення. Зазвичай доступ зберігається до кінця вже оплаченого періоду, якщо акаунт не потрібно призупинити з правомірної причини. Після чинного скасування нове списання не здійснюється, якщо користувач не підписався знову."],
    ["Stripe і сторонні витрати", "Керування білінгом здійснюється через Stripe Billing Portal, якщо Stripe використовується для конкретної активації. Користувач відповідає за витрати, які безпосередньо стягують Etsy, Telegram, AI-провайдери чи інші треті сторони."],
    ["Захист споживачів", rightsUk],
    ["Контакт", "Питання щодо підписки: support@enjoyagency.com.ua."]
  ] },
  refund: { title: "Повернення коштів та скасування", updated: "Оновлено: 28 серпня 2026", sections: [
    ["Як скасувати", "Скасуйте майбутні поновлення через Stripe Billing Portal, якщо він доступний, або зверніться на support@enjoyagency.com.ua."],
    ["Наслідки скасування", "Скасування запобігає майбутнім поновленням. Саме скасування не створює автоматичного повернення за вже оплачений і використаний період, якщо інше не вимагає закон."],
    ["Загальна політика повернення", "Платежі за підписку загалом не повертаються після того, як користувач отримав доступ і почав користуватися Lucy Seller Copilot. Це не обмежує обов’язкові права споживачів."],
    ["Коли повернення може бути доступним", "Повернення може бути доступним, якщо цього вимагає закон, сталася подвійна оплата, помилкове списання, сервіс істотно не був наданий погодженим способом і закон вимагає засобу захисту, або постачальник схвалив виняткове повернення."],
    ["Подвійне списання", "Якщо один платіж за підписку помилково стягнуто двічі, після перевірки повертається дубльована сума."],
    ["Розгляд запитів", "Якщо закон не надає автоматичного засобу захисту, дискреційний запит розглядає ФОП Піцина Жанна Вікторівна."],
    ["Захист споживачів і контакт", rightsUk + " Запит на повернення: support@enjoyagency.com.ua."]
  ] },
  cookies: { title: "Політика cookies", updated: "Оновлено: 28 серпня 2026", sections: [
    ["Що використовується зараз", "Lucy може використовувати строго необхідне browser storage, authentication/session storage, security storage, мовну перевагу та налаштування інтерфейсу. Вибір UA/EN зберігається через localStorage."],
    ["Строго необхідні технології", "Ці технології потрібні для базової роботи, автентифікації, безпеки та збереження локальних налаштувань."],
    ["Аналітика і маркетинг", "Ми не заявляємо про Google Analytics, Meta Pixel, рекламні або marketing cookies. Якщо такі технології буде введено, цю політику та controls згоди буде оновлено, якщо цього вимагає закон."],
    ["Контакт", "Питання щодо cookies: support@enjoyagency.com.ua."]
  ] },
  "ai-disclaimer": { title: "Застереження щодо AI", updated: "Оновлено: 28 серпня 2026", sections: [
    ["AI у Lucy", "Lucy Seller Copilot використовує AI-технології та може взаємодіяти зі сторонніми AI-провайдерами."],
    ["Можливі помилки", "AI може неправильно зрозуміти контекст, надати неповну інформацію, допустити фактичні помилки, запропонувати недоречне SEO або не врахувати останні зміни політик/API Etsy."],
    ["Немає гарантій", "Lucy не гарантує продажі, рейтинг, дохід, конверсію, видимість, схвалення маркетплейсом або юридичну відповідність."],
    ["Перевірка користувачем", "Перед використанням або публікацією перевіряйте зміни лістингів, SEO-контент, ціни, формулювання політик і дії автоматизації."],
    ["Не професійна консультація", "Lucy не є адвокатом, податковим консультантом, бухгалтером або фінансовим радником. AI-вивід не замінює професійну консультацію."]
  ] },
  "acceptable-use": { title: "Правила допустимого використання", updated: "Оновлено: 28 серпня 2026", sections: [
    ["Заборонене використання", "Заборонені незаконне використання, шахрайство, порушення інтелектуальної власності, крадіжка облікових даних, несанкціонований доступ, шкідлива автоматизація, спам, оманлива діяльність на маркетплейсі та malware."],
    ["Платформи та API", "Не обходьте обмеження Etsy або інших API, rate limits чи засоби безпеки. Не здійснюйте несанкціонований scraping, якщо це заборонено, і дотримуйтеся умов сторонніх платформ."],
    ["Застосування", "Доступ може бути призупинено або припинено у разі серйозного зловживання, ризику безпеці, незаконних дій або порушення цих правил."],
    ["Контакт", "Повідомлення про зловживання: support@enjoyagency.com.ua."]
  ] }
};

const en: Record<string, LegalDocument> = {
  terms: { title: "Terms of Service", updated: "Updated: August 28, 2026", sections: [["Provider", providerEn], ["About Lucy Seller Copilot", "Lucy Seller Copilot is a subscription SaaS/AI service for Etsy sellers. It helps with shop and listing analysis, SEO recommendations, keyword and competitor research, niche research, draft creation, listing updates, image workflows, reporting, automation, Telegram delivery, and AI chat."], ["Eligibility and capacity", "Users must have the legal capacity required to enter into this agreement under the laws applicable to them. If a user is below the age of legal capacity in their jurisdiction, they may use the service only with the involvement and consent of a parent or legal guardian where legally permitted. Users must also meet third-party platform requirements, including Etsy."], ["No guaranteed results", "The service does not guarantee sales, Etsy ranking, revenue, conversion increases, visibility, marketplace approval, or error-free AI output."], ["Seller responsibility", "The seller remains responsible for products, listings, intellectual property rights, marketplace compliance, prices, taxes, shipping, customer service, and final publishing decisions."], ["Third-party services", "Lucy may interact with Etsy, OpenAI/ChatGPT, Anthropic/Claude, Telegram, payment processors, hosting, databases, and email providers. Lucy is independent and is not Etsy; it is not endorsed by Etsy, OpenAI, Anthropic, Telegram, or another platform."], ["Etsy availability", "Features may change or become unavailable because of Etsy API changes, platform restrictions, OAuth changes, outages, policy changes, or rate limits."], ["AI output", "AI text, SEO recommendations, analysis, and research are informational assistance. Review important changes before publishing."], ["Accounts and security", "Users are responsible for login credentials, authorized Etsy connections, and activity under their account."], ["Subscription", "PRO PLAN is $59 USD/month for 1 Etsy store. MULTI STORE is $99 USD/month for up to 5 Etsy stores. Subscriptions bill monthly and automatically renew until cancelled."], ["Suspension and termination", "Access may be suspended or terminated for fraud, illegal activity, abuse, security threats, Terms violations, API/security circumvention, or non-payment."], ["Intellectual property", "The Lucy interface, brand, software, and proprietary materials remain owned by the provider or applicable licensors. Users retain rights in uploaded content, subject to processing rights needed to provide the service."], ["Liability", "To the extent permitted by law, the provider is not liable for indirect losses, lost profits, or decisions based on the service. This does not exclude liability that cannot legally be excluded."], ["Governing law and consumer rights", "Ukrainian law governs the service. " + rightsEn], ["Contact", providerEn]] },
  privacy: { title: "Privacy Policy", updated: "Updated: August 28, 2026", sections: [["Controller", providerEn], ["Account data", "We may process name, email, authentication information, company information, country/region, phone if provided, language, timezone, and preferences."], ["Connected Etsy data", "Depending on API permissions, this may include shop information, shop ID, listings, drafts, listing images/videos, sections, reviews, shop statistics, orders and sales data, revenue/financial metrics where available through authorized API access, and OAuth connection state. Etsy Ads is not supported or claimed."], ["AI and chat data", "Prompts, chat messages, listing text, research requests, and shop/listing data needed to answer a request may be processed."], ["Telegram", "Telegram user/chat identifiers needed for delivery, delivery settings, and reports or notifications sent may be processed."], ["Subscription and billing", "Subscription status, plan, billing/customer identifiers, and payment status may be processed. Lucy does not store full card details in its interface; payment card information is handled by the payment processor where applicable."], ["Technical data", "IP address where logged, browser/device information, timestamps, security and error logs, and session information may be processed."], ["Purposes", "Data supports providing Lucy, authentication, Etsy connection, requested operations, AI responses, reports, Telegram notifications, subscriptions, support, security, fraud prevention, legal obligations, and reliability."], ["Legal bases", "Depending on the context, processing may rely on performance of contract, legitimate interests, consent where required, or compliance with legal obligations. The basis depends on the data and jurisdiction."], ["Providers and transfers", "Provider categories may include AI, hosting/cloud/database, payment processing, transactional email, Telegram, and Etsy APIs. We do not claim a provider receives production data before it is actually live. Providers may process data outside Ukraine; appropriate safeguards will be used where required."], ["Retention", "We retain personal data for as long as reasonably necessary to provide the service, comply with legal obligations, resolve disputes, enforce agreements, and maintain security. More specific periods may be published later."], ["Rights and requests", "Depending on applicable law, users may have rights to access, correction, deletion, restriction, objection, portability, withdrawal of consent, and complaint to a competent supervisory authority. Contact support@enjoyagency.com.ua for access, correction, deletion, export, or privacy support requests. Do not send secrets."]] },
  subscription: { title: "Subscription & Billing Policy", updated: "Updated: August 28, 2026", sections: [["Plans", "PRO PLAN — $59 USD/month, 1 Etsy store. MULTI STORE — $99 USD/month, up to 5 Etsy stores. There are no annual, lifetime, or free-trial plans."], ["Monthly recurring billing", "Subscription begins after successful payment/activation, bills monthly, and automatically renews until cancelled. Price and store limits are shown before purchase."], ["Plan changes", "Upgrades or downgrades may affect future billing according to the payment provider confirmation."], ["Failed payments", "A failed payment can suspend paid functionality. Users are responsible for maintaining valid payment details."], ["Cancellation and access", "Users can cancel future renewals. Unless otherwise stated, access remains available through the already paid billing period unless the account must be suspended for a valid reason. No additional charge occurs after effective cancellation unless the user subscribes again."], ["Stripe and third-party costs", "Billing is managed through the Stripe Billing Portal where Stripe is used for the activation. Users remain responsible for third-party costs charged directly by Etsy, Telegram, AI providers, or other third parties."], ["Consumer rights", rightsEn], ["Contact", "Subscription support: support@enjoyagency.com.ua."]] },
  refund: { title: "Refund & Cancellation Policy", updated: "Updated: August 28, 2026", sections: [["How to cancel", "Cancel future renewals through the Stripe Billing Portal where available, or contact support@enjoyagency.com.ua."], ["Cancellation effect", "Cancellation prevents future renewals. Cancellation alone does not automatically create a refund for a period already paid and used, except where required by law."], ["General refund policy", "Subscription payments are generally non-refundable after the user has received access to and begun using Lucy Seller Copilot. This does not override mandatory consumer rights."], ["When a refund may be available", "A refund may be available where required by applicable law, a duplicate payment occurred, an erroneous charge occurred, the service materially failed to be provided as agreed and applicable law requires a remedy, or the provider approves an exceptional refund."], ["Duplicate charge", "If the same subscription payment is charged twice in error, the duplicate charge will be refunded after verification."], ["Discretionary review", "Except where the law grants an automatic remedy, discretionary refund requests are reviewed by Sole Proprietor Zhanna Pitsyna."], ["Consumer rights and contact", rightsEn + " Refund requests: support@enjoyagency.com.ua."]] },
  cookies: { title: "Cookie Policy", updated: "Updated: August 28, 2026", sections: [["What is used now", "Lucy may use strictly necessary browser storage, authentication/session storage, security storage, language preference, and interface preferences. The UA/EN setting may use localStorage."], ["Strictly necessary technologies", "These support basic operation, authentication, security, and local preferences."], ["Analytics and marketing", "We do not claim Google Analytics, Meta Pixel, advertising cookies, or marketing cookies. If analytics or marketing technologies are introduced later, this policy and consent controls will be updated where required."], ["Contact", "Cookie questions: support@enjoyagency.com.ua."]] },
  "ai-disclaimer": { title: "AI Disclaimer", updated: "Updated: August 28, 2026", sections: [["AI in Lucy", "Lucy Seller Copilot uses AI technologies and may interact with third-party AI providers."], ["Possible errors", "AI may misunderstand context, provide incomplete information, make factual errors, produce inappropriate SEO recommendations, or fail to reflect the latest Etsy policy/API changes."], ["No guarantees", "Lucy does not guarantee sales, ranking, revenue, conversion, visibility, marketplace approval, or legal compliance."], ["User review", "Review listing changes, SEO content, pricing decisions, policy wording, and automation actions before relying on or publishing important changes."], ["Not professional advice", "Lucy is not a lawyer, tax advisor, accountant, or financial advisor. AI suggestions do not replace professional advice."]] },
  "acceptable-use": { title: "Acceptable Use Policy", updated: "Updated: August 28, 2026", sections: [["Prohibited use", "Unlawful use, fraud, intellectual property infringement, stolen credentials, unauthorized account access, malicious automation, spam, deceptive marketplace activity, and malware are prohibited."], ["Platforms and APIs", "Do not circumvent Etsy or other API restrictions, rate limits, or security controls. Do not perform unauthorized scraping where prohibited, and follow third-party platform terms."], ["Enforcement", "Access may be suspended or terminated for serious abuse, security risks, illegal activity, or violations of these rules."], ["Contact", "Abuse reports: support@enjoyagency.com.ua."]] }
};

export const legalDocuments: Record<LegalLocale, Record<string, LegalDocument>> = { uk, en };
export const legalSlugs = ["terms", "privacy", "subscription", "refund", "cookies", "ai-disclaimer", "acceptable-use"] as const;
