"use client";

import { useState } from "react";
import { BookOpenText, Plus, Search, Send, X } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import { useSession } from "@/lib/session";

const promptKeys = ["chat.starter.analyze.1", "chat.starter.create.1", "chat.starter.research.1", "chat.starter.research.2"];

export default function ChatPage() {
  const { t } = useI18n();
  const { primaryShop } = useSession();
  const [promptLibraryOpen, setPromptLibraryOpen] = useState(false);
  const [draft, setDraft] = useState("");
  const [context, setContext] = useState("shop");
  const contextLabel = context === "shop" ? primaryShop?.name ?? t("chat.simple.noShop") : context === "listing" ? t("chat.simple.currentListing") : t("chat.simple.noContext");

  return <main className="min-h-screen bg-[#F7F4F1] px-4 pb-6 pt-6 sm:px-6 lg:px-8 lg:pt-8"><div className="mx-auto max-w-[1120px]">
    <header className="flex flex-col justify-between gap-4 border-b border-charcoal/[0.08] pb-6 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-semibold tracking-[-0.05em] text-charcoal">{t("chat.simple.title")}</h1><p className="mt-2 max-w-xl text-[12px] leading-5 text-charcoal/55">{t("chat.simple.subtitle")}</p></div><div className="flex gap-2"><button type="button" onClick={() => setDraft("")} className="inline-flex h-9 items-center gap-2 rounded-[10px] border border-charcoal/[0.1] bg-white px-3 text-[11px] font-semibold text-charcoal/70"><Plus size={14}/>{t("chat.simple.new")}</button><button type="button" onClick={() => setPromptLibraryOpen(true)} className="inline-flex h-9 items-center gap-2 rounded-[10px] border border-charcoal/[0.1] bg-white px-3 text-[11px] font-semibold text-charcoal/70"><BookOpenText size={14}/>{t("chat.simple.promptLibrary")}</button></div></header>
    <section className="mt-6 overflow-hidden rounded-[18px] border border-charcoal/[0.07] bg-white shadow-[0_18px_50px_rgba(51,51,51,0.04)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-charcoal/[0.08] px-4 py-3"><div className="flex items-center gap-2 text-[11px] text-charcoal/55"><span className="font-semibold text-charcoal/40">{t("chat.simple.context")}</span><span className="rounded-full bg-[#FCFAF8] px-3 py-1.5 text-charcoal/65">{contextLabel}</span></div><div className="flex gap-1">{[["shop", t("chat.simple.currentShop")], ["listing", t("chat.simple.currentListing")], ["none", t("chat.simple.noContext")]].map(([key, label]) => <button key={key} type="button" onClick={() => setContext(key)} className={`rounded-[8px] px-2.5 py-1.5 text-[11px] font-semibold ${context === key ? "bg-charcoal text-white" : "text-charcoal/50"}`}>{label}</button>)}</div></div><div className="min-h-[300px] p-5 sm:p-8"><div className="grid min-h-[240px] place-items-center rounded-[14px] border border-dashed border-charcoal/[0.12] bg-[#FCFAF8] px-5 text-center"><div><p className="text-[16px] font-semibold text-charcoal">{t("chat.empty.title")}</p><p className="mt-2 text-[12px] text-charcoal/50">{t("chat.empty.description")}</p></div></div></div><div className="border-t border-charcoal/[0.08] bg-[#FBFAF8] p-4"><div className="mb-3 flex flex-wrap gap-2">{promptKeys.map(key => <button key={key} type="button" onClick={() => setDraft(t(key))} className="rounded-[10px] border border-charcoal/[0.1] bg-white px-3 py-2 text-[11px] text-charcoal/60">{t(key)}</button>)}</div><div className="flex items-end gap-2 rounded-[14px] border border-charcoal/[0.1] bg-white p-2"><textarea value={draft} onChange={event => setDraft(event.target.value)} rows={1} placeholder={t("chat.simple.placeholder")} className="min-h-[42px] min-w-0 flex-1 resize-none bg-transparent px-2 py-2.5 text-[13px] outline-none placeholder:text-charcoal/35"/><button type="button" disabled={!draft.trim()} className="grid size-9 shrink-0 place-items-center rounded-[9px] bg-terracotta text-white disabled:cursor-not-allowed disabled:opacity-40" aria-label={t("chat.simple.send")}><Send size={15}/></button></div><p className="mt-2 text-[11px] text-charcoal/40">{t("chat.simple.disclaimer")}</p></div></section>
    {promptLibraryOpen && <div className="fixed inset-0 z-50 flex items-center justify-end bg-charcoal/25"><aside className="h-full w-full max-w-[380px] overflow-y-auto bg-[#FBFAF8] p-5 shadow-[-16px_0_50px_rgba(51,51,51,0.12)]"><div className="flex items-center justify-between border-b border-charcoal/[0.08] pb-4"><h2 className="text-[17px] font-semibold text-charcoal">{t("chat.simple.promptLibrary")}</h2><button type="button" onClick={() => setPromptLibraryOpen(false)} aria-label={t("chat.simple.close")}><X size={17}/></button></div><div className="mt-4 space-y-2">{promptKeys.map(key => <button key={key} type="button" onClick={() => { setDraft(t(key)); setPromptLibraryOpen(false); }} className="flex w-full items-center gap-2 rounded-[11px] bg-white p-3 text-left text-[12px] text-charcoal/65"><Search size={14} className="text-terracotta"/>{t(key)}</button>)}</div></aside></div>}
  </div></main>;
}
