"use client";

import { useEffect, useState } from "react";
import * as XLSX from "xlsx";
import { ArrowLeft, ArrowRight, Check, Upload } from "lucide-react";
import { createEtsyDraft, generateLucyListing, getEtsyReadinessProfiles, getEtsyShippingProfiles, searchEtsyTaxonomy } from "@/lib/api/etsy";
import type { EtsyDraftInput, EtsyProfile } from "@/lib/api/types";

const headers = ["Назва товару", "Опишіть товар для Lucy", "Ціна, USD", "Кількість", "Тип", "Матеріали", "Розміри / варіації", "Колір", "Персоналізація", "Фото URL", "Примітки"];
const stages = ["listings.bulk.stepUpload", "listings.bulk.stepPreview", "listings.bulk.stepLucy", "listings.bulk.stepCategory", "listings.bulk.stepValidation", "listings.bulk.stepCreation"];
type Row = EtsyDraftInput & { id: number; productDescription: string; categoryText: string; selected: boolean; status: "waiting" | "creating" | "created" | "error"; error?: string };
type Category = { taxonomyId: string | number; name: string; path: string | string[] };
function text(value: unknown) { return String(value ?? "").replace(/^\uFEFF/, "").trim(); }
function split(value: unknown) { return text(value).split(/[;,]/).map((item) => item.trim()).filter(Boolean); }
function parse(value: string | ArrayBuffer) { const isText = typeof value === "string"; const sourceText = isText ? value.replace(/^\uFEFF/, "") : ""; const source: string | ArrayBuffer = isText ? sourceText : value; const workbook = XLSX.read(source, { type: isText ? "string" : "array", ...(isText ? { FS: (sourceText.match(/;/g) ?? []).length > (sourceText.match(/,/g) ?? []).length ? ";" : "," } : {}) }); const sheetName = workbook.SheetNames.find((name) => name === "Товари") ?? workbook.SheetNames.find((name) => !["Приклад", "Як заповнювати"].includes(name)) ?? workbook.SheetNames[0]; return XLSX.utils.sheet_to_json<unknown[]>(workbook.Sheets[sheetName], { header: 1, defval: "" }); }
function makeRow(values: unknown[], indexes: Record<string, number>, id: number): Row { const get = (header: string) => values[indexes[header]]; const type = ["digital", "download", "цифровий"].includes(text(get(headers[4])).toLowerCase()) ? "download" : "physical"; return { id, productDescription: text(get(headers[1])), title: text(get(headers[0])), description: text(get(headers[1])), price: Number.parseFloat(text(get(headers[2]))), quantity: Number.parseInt(text(get(headers[3])), 10), type, materials: split(get(headers[5])), tags: [], whoMade: "i_did", whenMade: "made_to_order", categoryText: "", selected: true, status: "waiting" }; }

export function BulkListingWorkflow({ t, onBack }: { t: (key: string) => string; onBack: () => void }) {
  const [stage, setStage] = useState(0); const [rows, setRows] = useState<Row[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const update = (id: number, field: keyof Row, value: string | number | boolean) => setRows((current) => current.map((row) => row.id === id ? { ...row, [field]: value } : row));
  const importFile = (file: File) => { const reader = new FileReader(); reader.onload = () => { try { const values = parse(reader.result as string | ArrayBuffer); const first = (values[0] ?? []).map(text); const indexes = Object.fromEntries(headers.map((header) => [header, first.indexOf(header)])); setRows(values.slice(1).filter((row) => row.some((cell) => text(cell))).map((row, index) => makeRow(row, indexes, index + 1))); setStage(1); setError(""); } catch { setError(t("listings.bulk.importError")); } }; if (file.name.toLowerCase().endsWith(".csv")) reader.readAsText(file, "utf-8"); else reader.readAsArrayBuffer(file); };
  const validate = (row: Row) => !row.title?.trim() ? t("listings.validation.title") : !row.description?.trim() ? t("listings.bulk.errorDescription") : !row.price || row.price <= 0 ? t("listings.bulk.errorPrice") : !row.quantity || row.quantity <= 0 ? t("listings.bulk.errorQuantity") : !row.taxonomyId ? t("listings.bulk.errorCategory") : row.type === "physical" && !row.shippingProfileId ? t("listings.bulk.errorShipping") : row.type === "physical" && !row.readinessStateId ? t("listings.bulk.errorReadiness") : "";
  async function enrich() { setBusy(true); for (const row of rows) { try { const result = await generateLucyListing(`${row.title}. ${row.description}`, "uk", row.type === "download" ? "download" : "physical"); setRows((current) => current.map((item) => item.id === row.id ? { ...item, title: item.title || result.title, description: item.description || result.description, tags: item.tags?.length ? item.tags : result.tags, materials: item.materials?.length ? item.materials : result.materials } : item)); } catch { setError(t("listings.bulk.enrichmentError")); } } setBusy(false); setStage(3); }
  async function createDrafts() { setBusy(true); for (const row of rows) { const issue = validate(row); if (issue) { update(row.id, "error", issue); continue; } update(row.id, "status", "creating"); try { await createEtsyDraft(row); update(row.id, "status", "created"); } catch { update(row.id, "status", "error"); } } setBusy(false); }
  return <section className="mt-6"><header className="flex items-center justify-between"><h2 className="text-2xl font-semibold text-charcoal">{t("listings.bulk.title")}</h2><button type="button" onClick={onBack} className="text-[10px] font-semibold text-terracotta">{t("listings.workspace.back")}</button></header><nav className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-6">{stages.map((key, index) => <button type="button" key={key} disabled={index > stage} onClick={() => setStage(index)} className={`rounded-[9px] px-2 py-2 text-[10px] font-semibold ${index === stage ? "bg-terracotta text-white" : index < stage ? "bg-[#F3E9DF] text-terracotta" : "bg-[#FCFAF8] text-charcoal/40"}`}>{index < stage && <Check size={12} className="mr-1 inline"/>}{index + 1}. {t(key)}</button>)}</nav>{error && <p role="alert" className="mt-3 text-[11px] text-[#B34A35]">{error}</p>}<div className="mt-5 rounded-[20px] border border-charcoal/[0.07] bg-white p-5">{stage === 0 && <UploadStep t={t} importFile={importFile}/>} {stage === 1 && <PreviewStep t={t} rows={rows} update={update}/>} {stage === 2 && <LucyStep t={t} busy={busy} onClick={() => void enrich()}/>} {stage === 3 && <CategoryStep t={t} rows={rows} update={update}/>} {stage === 4 && <ValidationStep t={t} rows={rows} validate={validate}/>} {stage === 5 && <CreationStep t={t} rows={rows} busy={busy} onClick={() => void createDrafts()}/>}<footer className="mt-6 flex justify-between border-t pt-4"><button type="button" onClick={() => stage ? setStage(stage - 1) : onBack()} className="inline-flex items-center gap-1 border px-3 py-2 text-[11px] font-semibold"><ArrowLeft size={14}/>{t("listings.workspace.back")}</button>{stage < 5 && <button type="button" disabled={!rows.length || busy} onClick={() => setStage(stage + 1)} className="inline-flex items-center gap-1 bg-terracotta px-4 py-2 text-[11px] font-semibold text-white disabled:opacity-40">{t("listings.wizard.next")}<ArrowRight size={14}/></button>}</footer></div></section>;
}

function UploadStep({ t, importFile }: { t: (key: string) => string; importFile: (file: File) => void }) { return <div><div className="flex gap-3"><a href="/templates/Lucy_Etsy_Bulk_Template_PRO.xlsx" download="Lucy_Etsy_Bulk_Template_PRO.xlsx" className="border px-3 py-2 text-[11px] font-semibold">{t("listings.bulk.downloadTemplate")}</a><a href="/templates/Lucy_Etsy_Bulk_Template_PRO.csv" download="Lucy_Etsy_Bulk_Template_PRO.csv" className="py-2 text-[11px] font-semibold text-terracotta">{t("listings.bulk.csvVersion")}</a></div><label className="mt-6 flex min-h-40 cursor-pointer flex-col items-center justify-center border border-dashed bg-[#FCFAF8] text-[11px] text-charcoal/55"><Upload size={20} className="mb-2 text-terracotta"/>{t("listings.bulk.uploadFile")}<input type="file" accept=".xlsx,.csv" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) importFile(file); }}/></label></div>; }
function PreviewStep({ t, rows, update }: { t: (key: string) => string; rows: Row[]; update: (id: number, field: keyof Row, value: string | number | boolean) => void }) { return <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-[11px]"><thead><tr className="border-b text-charcoal/45"><th className="py-2">{t("listings.bulk.name")}</th><th>{t("listings.price")}</th><th>{t("listings.quantity")}</th><th>{t("listings.fields.type")}</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b"><td className="py-2"><input value={row.title} onChange={(event) => update(row.id, "title", event.target.value)} className="h-8 w-full border px-2"/></td><td><input type="number" value={row.price || ""} onChange={(event) => update(row.id, "price", Number(event.target.value))} className="h-8 w-20 border px-2"/></td><td><input type="number" value={row.quantity || ""} onChange={(event) => update(row.id, "quantity", Number(event.target.value))} className="h-8 w-16 border px-2"/></td><td>{row.type}</td></tr>)}</tbody></table></div>; }
function LucyStep({ t, busy, onClick }: { t: (key: string) => string; busy: boolean; onClick: () => void }) { return <div><p className="text-[12px] text-charcoal/55">{t("listings.bulk.helper")}</p><button type="button" disabled={busy} onClick={onClick} className="mt-5 bg-terracotta px-4 py-2 text-[11px] font-semibold text-white">{busy ? t("listings.bulk.enriching") : t("listings.bulk.completeLucy")}</button></div>; }
function CategoryStep({ t, rows, update }: { t: (key: string) => string; rows: Row[]; update: (id: number, field: keyof Row, value: string | number | boolean) => void }) {
  const [shipping, setShipping] = useState<EtsyProfile[]>([]); const [readiness, setReadiness] = useState<EtsyProfile[]>([]); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); const [queries, setQueries] = useState<Record<number, string>>({}); const [results, setResults] = useState<Record<number, Category[]>>({});
  useEffect(() => { Promise.all([getEtsyShippingProfiles(), getEtsyReadinessProfiles()]).then(([a, b]) => { setShipping(a.profiles); setReadiness(b.profiles); }).catch(() => setFailed(true)).finally(() => setLoading(false)); }, []);
  async function search(rowId: number, value: string) { setQueries((current) => ({ ...current, [rowId]: value })); if (value.trim().length < 2) return; try { const matches = await searchEtsyTaxonomy(value); setResults((current) => ({ ...current, [rowId]: matches })); } catch { setResults((current) => ({ ...current, [rowId]: [] })); } }
  return <div className="space-y-4">{rows.map((row) => <div key={row.id} className="space-y-2 border p-3"><p className="text-[11px] font-semibold">{row.title}</p><input value={queries[row.id] ?? row.categoryText} onChange={(event) => void search(row.id, event.target.value)} placeholder={t("listings.fields.category")} className="h-9 w-full border px-2 text-[11px]"/><div className="space-y-1">{(results[row.id] ?? []).map((category) => <button type="button" key={String(category.taxonomyId)} onClick={() => { update(row.id, "taxonomyId", category.taxonomyId); update(row.id, "categoryText", category.path instanceof Array ? category.path.join(" / ") : category.path); }} className="block w-full text-left text-[10px] text-charcoal/65">{category.name} · {category.path instanceof Array ? category.path.join(" / ") : category.path}</button>)}</div>{row.type === "download" ? <p className="text-[10px] text-charcoal/55">{t("listings.digital.fulfillmentNote")}</p> : loading ? <p className="text-[10px] text-charcoal/45">{t("listings.bulk.loadingProfiles")}</p> : failed ? <p className="text-[10px] text-[#B34A35]">{t("listings.bulk.profileError")}</p> : <div className="grid gap-2 sm:grid-cols-2"><select value={String(row.shippingProfileId ?? "")} onChange={(event) => update(row.id, "shippingProfileId", event.target.value)} className="h-9 border px-2 text-[11px]"><option value="">{shipping.length ? t("listings.fields.shipping") : t("listings.bulk.noShippingProfiles")}</option>{shipping.map((profile) => <option key={String(profile.id)} value={String(profile.id)}>{profile.name}</option>)}</select><select value={String(row.readinessStateId ?? "")} onChange={(event) => update(row.id, "readinessStateId", event.target.value)} className="h-9 border px-2 text-[11px]"><option value="">{readiness.length ? t("listings.fields.readiness") : t("listings.bulk.noReadinessProfiles")}</option>{readiness.map((profile) => <option key={String(profile.id)} value={String(profile.id)}>{profile.name}</option>)}</select></div>}</div>)}</div>;
}
function ValidationStep({ t, rows, validate }: { t: (key: string) => string; rows: Row[]; validate: (row: Row) => string }) { return <div className="space-y-2">{rows.map((row) => <div key={row.id} className="flex justify-between border p-3 text-[11px]"><span>{row.title}</span><span className={validate(row) ? "text-[#B34A35]" : "text-[#2B7655]"}>{validate(row) || t("listings.bulk.ready")}</span></div>)}</div>; }
function CreationStep({ t, rows, busy, onClick }: { t: (key: string) => string; rows: Row[]; busy: boolean; onClick: () => void }) { return <div><div className="space-y-2 text-[11px]">{rows.map((row) => <div key={row.id} className="flex justify-between"><span>{row.title}</span><span>{row.status === "created" ? t("listings.bulk.created") : row.status === "error" ? t("listings.bulk.errorCreate") : t("listings.bulk.ready")}</span></div>)}</div><button type="button" disabled={busy} onClick={onClick} className="mt-5 bg-terracotta px-4 py-2 text-[11px] font-semibold text-white">{t("listings.bulk.createDrafts")}</button></div>; }
