"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, Check, FileText, ImageIcon, LineChart, Search, ShieldCheck, Sparkles } from "lucide-react";
import { LanguageSwitcher, useI18n } from "@/lib/i18n";

const features = [
  { titleKey: "public.features.research", icon: Search, descriptionKey: "public.features.researchDesc", items: ["public.item.niches", "public.item.trends", "public.item.reviews"] },
  { titleKey: "public.features.competitors", icon: BarChart3, descriptionKey: "public.features.competitorsDesc", items: ["public.item.shopPatterns", "public.item.productGaps", "public.item.positioning"] },
  { titleKey: "public.features.keywords", icon: Search, descriptionKey: "public.features.keywordsDesc", items: ["public.item.demandSignals", "public.item.competition", "public.item.keywordIdeas"] },
  { titleKey: "public.features.seo", icon: FileText, descriptionKey: "public.features.seoDesc", items: ["public.item.titles", "public.item.tags", "public.item.descriptions"] },
  { titleKey: "public.features.images", icon: ImageIcon, descriptionKey: "public.features.imagesDesc", items: ["public.item.lifestyle", "public.item.infographics", "public.item.mockups"] },
  { titleKey: "public.features.reports", icon: LineChart, descriptionKey: "public.features.reportsDesc", items: ["public.item.weeklyReports", "public.item.growthSignals", "public.item.watchlist"] },
];

const workflow = ["public.workflow.niche", "public.workflow.competitors", "public.workflow.keywords", "public.workflow.seo", "public.workflow.images", "public.workflow.draft", "public.workflow.monitoring"];
const containerClass = "mx-auto w-full max-w-[1280px] px-4 sm:px-6 lg:px-8";

function Flow({ t }: { t: (key: string) => string }) {
  return <div className="flex flex-wrap items-center gap-x-2 gap-y-2 text-xs text-[#333333]/70">{workflow.map((step, index) => <span key={step} className="inline-flex items-center gap-2"><span className="rounded-lg border border-[#333333]/10 bg-white px-2.5 py-2 font-semibold">{t(step)}</span>{index < workflow.length - 1 && <ArrowRight size={13} className="text-[#F74E03]" />}</span>)}</div>;
}

export default function PublicLanding() {
  const { t } = useI18n();
  return <main className="min-h-screen overflow-hidden bg-[#F7F4F1] text-[#333333]">
    <nav className={`${containerClass} flex h-[72px] items-center justify-between`}>
      <Link href="/" className="flex items-center"><Image src="/brand/lucy-logo-dark.png" alt="Lucy Seller Copilot" width={220} height={90} className="h-auto w-[170px] sm:w-[180px]" /></Link>
      <div className="flex items-center gap-2 sm:gap-3"><a href="#features" className="hidden px-2 text-xs font-medium text-[#333333]/65 sm:inline">{t("public.nav.features")}</a><Link href="/pricing" className="hidden px-2 text-xs font-medium text-[#333333]/65 sm:inline">{t("public.nav.pricing")}</Link><LanguageSwitcher /><Link href="/login" className="rounded-lg border border-[#333333]/12 bg-white px-3.5 py-2 text-xs font-semibold">{t("public.nav.signIn")}</Link><Link href="/signup" className="rounded-lg bg-[#F74E03] px-3.5 py-2 text-xs font-semibold text-white">{t("public.nav.start")}</Link></div>
    </nav>

    <section className={`${containerClass} relative grid min-h-[580px] gap-8 py-10 sm:py-12 lg:grid-cols-[1.12fr_0.88fr] lg:items-center lg:gap-12 lg:py-14`}>
      <div className="relative z-10"><p className="mb-3 inline-flex items-center gap-2 rounded-full border border-[#F74E03]/15 bg-[#F74E03]/5 px-2.5 py-1.5 text-[9px] font-semibold uppercase tracking-[0.16em] text-[#F74E03]"><span className="size-1.5 rounded-full bg-[#F74E03]" />{t("public.hero.badge")}</p><h1 className="max-w-[720px] text-[clamp(2.5rem,5.4vw,4.75rem)] font-semibold leading-[0.95] tracking-[-0.07em]">{t("public.hero.title")}</h1><p className="mt-5 max-w-[580px] text-base leading-7 text-[#333333]/62">{t("public.hero.description")}</p><div className="mt-6 flex flex-wrap gap-2.5"><Link href="/signup" className="inline-flex items-center gap-2 rounded-xl bg-[#F74E03] px-4 py-3 text-sm font-semibold text-white shadow-[0_12px_26px_rgba(247,78,3,0.18)]">{t("public.nav.start")} <ArrowRight size={15} /></Link><a href="#features" className="rounded-xl border border-[#333333]/12 bg-white px-4 py-3 text-sm font-semibold">{t("public.hero.explore")}</a></div><p className="mt-4 text-[11px] text-[#333333]/45">{t("public.hero.note")}</p></div>
      <div className="relative min-h-[300px] rounded-[26px] border border-[#333333]/8 bg-white p-4 shadow-[0_18px_45px_rgba(51,51,51,0.08)] sm:p-5"><div className="relative flex h-full flex-col"><div className="flex items-center justify-between border-b border-[#333333]/8 pb-3"><div className="flex items-center gap-2"><Image src="/lucy/lucy-updated.png" alt="Lucy" width={38} height={38} className="size-9 rounded-lg bg-[#F7F4F1] object-contain" /><div><p className="text-xs font-semibold">{t("public.preview.workspace")}</p><p className="text-[9px] text-[#333333]/45">{t("public.preview.subtitle")}</p></div></div><Sparkles className="text-[#F74E03]" size={16} /></div><div className="mt-3 flex gap-1 overflow-hidden text-[9px] font-semibold text-[#333333]/48"><span className="rounded-md bg-[#F74E03]/10 px-2 py-1 text-[#F74E03]">{t("public.preview.research")}</span><span className="px-2 py-1">{t("public.preview.competitors")}</span><span className="px-2 py-1">{t("public.preview.keywords")}</span><span className="hidden px-2 py-1 sm:inline">{t("public.preview.seoListing")}</span></div><div className="mt-3 grid flex-1 grid-cols-[0.9fr_1.1fr] gap-3 rounded-xl bg-[#F7F4F1] p-3"><div><p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#333333]/35">{t("public.preview.research")}</p><p className="mt-2 text-xs font-semibold">{t("public.preview.niche")}</p><p className="mt-1 text-[10px] leading-4 text-[#333333]/50">{t("public.preview.nicheDescription")}</p><div className="mt-3 space-y-1.5 text-[9px] text-[#333333]/55"><p>{t("public.preview.competitors")} <span className="float-right font-semibold text-[#2D8158]">{t("public.preview.ready")}</span></p><p>{t("public.preview.keywords")} <span className="float-right font-semibold text-[#2D8158]">{t("public.preview.found")}</span></p><p>{t("public.preview.reports")} <span className="float-right text-[#333333]/35">{t("public.preview.preview")}</span></p></div></div><div className="rounded-lg border border-[#333333]/8 bg-white p-3"><p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#333333]/35">{t("public.preview.nextStep")}</p><p className="mt-2 text-xs font-semibold">{t("public.preview.createListing")}</p><p className="mt-1 text-[10px] leading-4 text-[#333333]/50">{t("public.preview.createDescription")}</p><div className="mt-4 h-1.5 rounded-full bg-[#333333]/10"><div className="h-full w-3/4 rounded-full bg-[#F74E03]" /></div><p className="mt-2 text-[9px] text-[#333333]/40">{t("public.preview.followUp")}</p></div></div></div></div>
    </section>

    <section id="features" className="border-y border-[#333333]/8 bg-white py-16"><div className={containerClass}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-[9px] font-semibold uppercase tracking-[0.16em] text-[#F74E03]">{t("public.features.eyebrow")}</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.055em] sm:text-4xl">{t("public.features.title")}</h2></div><p className="max-w-sm text-sm leading-6 text-[#333333]/52">{t("public.features.description")}</p></div><div className="mt-8 grid items-stretch gap-5 sm:grid-cols-2 lg:grid-cols-3">{features.map(({ titleKey, icon: Icon, descriptionKey, items }) => <article key={titleKey} className="flex h-full flex-col rounded-[18px] border border-[#333333]/8 bg-[#F7F4F1] p-4"><div className="flex items-start justify-between"><div className="grid size-8 place-items-center rounded-lg bg-white text-[#F74E03]"><Icon size={16} /></div><span className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#333333]/30">{t("public.features.explore")}</span></div><h3 className="mt-4 text-base font-semibold">{t(titleKey)}</h3><p className="mt-1 text-xs text-[#333333]/52">{t(descriptionKey)}</p><ul className="mt-3 space-y-1.5 text-[11px] text-[#333333]/65">{items.map((item) => <li key={item} className="flex gap-1.5"><Check size={12} className="mt-0.5 shrink-0 text-[#2D8158]" />{t(item)}</li>)}</ul></article>)}</div></div></section>

    <section className={`${containerClass} py-16`}><div className="rounded-[22px] border border-[#333333]/8 bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 border-b border-[#333333]/8 pb-5 sm:flex-row sm:items-center"><div><p className="text-[9px] font-semibold uppercase tracking-[0.16em] text-[#F74E03]">{t("public.workflow.eyebrow")}</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.05em]">{t("public.workflow.title")}</h2></div><p className="max-w-sm text-xs leading-5 text-[#333333]/50">{t("public.workflow.description")}</p></div><div className="pt-5"><Flow t={t} /></div></div></section>

    <section className="border-y border-[#333333]/8 bg-[#E7E0DA]/45 py-16"><div className={`${containerClass} grid gap-7 lg:grid-cols-[0.72fr_1.28fr] lg:items-start`}><div><p className="text-[9px] font-semibold uppercase tracking-[0.16em] text-[#F74E03]">{t("public.why.eyebrow")}</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.055em]">{t("public.why.title")}</h2></div><div className="grid gap-5 sm:grid-cols-2">{["public.why.ai", "public.why.research", "public.why.recommendations", "public.why.safety"].map((item) => <div key={item} className="flex gap-2.5 rounded-xl bg-white p-3 text-xs font-medium"><ShieldCheck className="shrink-0 text-[#F74E03]" size={16} />{t(item)}</div>)}</div></div></section>

    <section className={`${containerClass} py-16`}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-[9px] font-semibold uppercase tracking-[0.16em] text-[#F74E03]">{t("public.pricing.eyebrow")}</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.055em]">{t("public.pricing.title")}</h2></div><Link href="/pricing" className="text-xs font-semibold text-[#F74E03]">{t("public.pricing.full")} <ArrowRight className="ml-1 inline" size={14} /></Link></div><div className="mt-7 grid items-stretch gap-5 md:grid-cols-2"><article className="flex h-full flex-col rounded-[18px] border border-[#333333]/8 bg-white p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#333333]/45">PRO</p><p className="mt-3 text-3xl font-semibold">$59<span className="text-xs font-normal text-[#333333]/45">{t("public.pricing.month")}</span></p><p className="mt-1 text-xs text-[#333333]/55">{t("public.pricing.oneShop")}</p><Link href="/signup" className="mt-auto inline-flex w-fit rounded-lg bg-[#333333] px-3.5 py-2.5 text-xs font-semibold text-white">{t("public.pricing.pro")}</Link></article><article className="flex h-full flex-col rounded-[18px] border border-[#F74E03]/20 bg-[#FFF9F5] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#F74E03]">MULTI STORE</p><p className="mt-3 text-3xl font-semibold">$99<span className="text-xs font-normal text-[#333333]/45">{t("public.pricing.month")}</span></p><p className="mt-1 text-xs text-[#333333]/55">{t("public.pricing.multiShop")}</p><Link href="/signup" className="mt-auto inline-flex w-fit rounded-lg bg-[#F74E03] px-3.5 py-2.5 text-xs font-semibold text-white">{t("public.pricing.multi")}</Link></article></div></section>

    <section className="bg-[#333333] py-14 text-white"><div className={`${containerClass} flex flex-col justify-between gap-5 sm:flex-row sm:items-center`}><div><p className="text-[9px] font-semibold uppercase tracking-[0.16em] text-[#F74E03]">{t("public.cta.eyebrow")}</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.05em] sm:text-3xl">{t("public.cta.title")}</h2><p className="mt-2 text-sm text-white/55">{t("public.cta.description")}</p></div><Link href="/signup" className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-[#F74E03] px-4 py-3 text-sm font-semibold">{t("public.cta.button")} <ArrowRight size={15} /></Link></div></section>
    <footer className={`${containerClass} flex justify-between gap-3 py-5 text-[11px] text-[#333333]/45`}><span>Lucy Seller Copilot</span><span>{t("public.footer.safety")}</span></footer>
  </main>;
}
