"use client";

import { useState } from "react";
import { Image as ImageIcon, LayoutTemplate, Sparkles, X } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import { LucyEmptyPreview } from "@/components/LucyEmptyPreview";

const primaryTypes = ["thumbnail", "lifestyle", "productInfo", "mockup"];
const templates = ["premium", "lifestyle", "mainThumbnail", "productFeatures", "materials", "giftPresentation", "seasonalStyling", "digitalMockup", "minimalScene", "workshop"];

export default function ImageStudioPage() {
  const { t } = useI18n();
  const [imageType, setImageType] = useState("thumbnail");
  const [template, setTemplate] = useState("premium");
  const [prompt, setPrompt] = useState("");
  const [templatesOpen, setTemplatesOpen] = useState(false);
  return <main className="min-h-screen px-4 pb-12 pt-6 sm:px-6 lg:px-8 lg:pt-8"><div className="mx-auto max-w-[1180px]">
    <header className="border-b border-charcoal/[0.08] pb-6"><h1 className="text-3xl font-semibold tracking-[-0.05em] text-charcoal">{t("imageStudio.title")}</h1><p className="mt-2 max-w-xl text-[12px] leading-5 text-charcoal/55">{t("imageStudio.subtitle")}</p></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-3">{["imageStudio.simple.stepType", "imageStudio.simple.stepProduct", "imageStudio.simple.stepCreate"].map((key, index) => <div key={key} className="flex items-center gap-3 rounded-[14px] border border-charcoal/[0.07] bg-white p-4"><span className="grid size-8 place-items-center rounded-full bg-charcoal text-[13px] font-semibold text-white">{index + 1}</span><span className="text-[13px] font-semibold text-charcoal">{t(key)}</span></div>)}</section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(320px,0.8fr)]"><section className="space-y-5"><section className="rounded-[16px] border border-charcoal/[0.07] bg-white p-5"><h2 className="text-[18px] font-semibold text-charcoal">{t("imageStudio.chooseImageType")}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{primaryTypes.map(type => <button key={type} type="button" onClick={() => setImageType(type)} className={`rounded-[12px] border p-4 text-left ${imageType === type ? "border-terracotta/25 bg-[#FFF8F3]" : "border-charcoal/[0.08] bg-[#FCFAF8]"}`}><ImageIcon size={18} className="text-terracotta"/><span className="mt-2 block text-[14px] font-semibold text-charcoal">{t(`imageStudio.type.${type}`)}</span></button>)}</div></section><section className="rounded-[16px] border border-charcoal/[0.07] bg-white p-5"><label className="block text-[13px] font-semibold text-charcoal">{t("imageStudio.customPrompt")}<textarea value={prompt} onChange={event => setPrompt(event.target.value)} rows={4} placeholder={t("imageStudio.promptPlaceholder")} className="mt-2 w-full resize-none rounded-[11px] border border-charcoal/[0.1] bg-[#FCFAF8] p-3 text-[13px] leading-5 outline-none focus:border-terracotta"/></label><label className="mt-4 block text-[13px] font-semibold text-charcoal">{t("imageStudio.simple.template")}<select value={template} onChange={event => setTemplate(event.target.value)} className="mt-2 h-10 w-full rounded-[10px] border border-charcoal/[0.1] bg-white px-3 text-[13px] font-normal">{templates.slice(0, 3).map(item => <option key={item} value={item}>{t(`imageStudio.template.${item}`)}</option>)}</select></label><button type="button" onClick={() => setTemplatesOpen(true)} className="mt-4 inline-flex h-9 items-center gap-2 rounded-[10px] border border-charcoal/[0.1] px-3 text-[11px] font-semibold text-charcoal/65"><LayoutTemplate size={14}/>{t("imageStudio.simple.browseTemplates")}</button></section></section><section className="rounded-[16px] border border-charcoal/[0.07] bg-white p-5"><h2 className="text-[18px] font-semibold text-charcoal">{t("imageStudio.previewWorkspace")}</h2><p className="mt-1 text-[11px] text-charcoal/45">{t(`imageStudio.type.${imageType}`)}</p><div className="mt-4"><LucyEmptyPreview size="large" title={t("imageStudio.empty.title")} description={t("imageStudio.empty.description")} /></div><button type="button" disabled className="mt-4 inline-flex h-10 w-full items-center justify-center gap-2 rounded-[10px] bg-terracotta text-[12px] font-semibold text-white disabled:cursor-not-allowed disabled:opacity-45"><Sparkles size={15}/>{t("imageStudio.generateUnavailable")}</button></section></div>
    <section className="mt-6 rounded-[16px] border border-charcoal/[0.07] bg-white p-5"><h2 className="text-[18px] font-semibold text-charcoal">{t("imageStudio.library")}</h2><div className="mt-4"><LucyEmptyPreview size="small" title={t("imageStudio.empty.libraryTitle")} description={t("imageStudio.empty.libraryDescription")} /></div></section>
    {templatesOpen && <div className="fixed inset-0 z-50 flex items-center justify-end bg-charcoal/25"><aside className="h-full w-full max-w-[380px] overflow-y-auto bg-[#FBFAF8] p-5"><div className="flex items-center justify-between"><h2 className="text-[17px] font-semibold text-charcoal">{t("imageStudio.simple.browseTemplates")}</h2><button type="button" onClick={() => setTemplatesOpen(false)} aria-label={t("imageStudio.simple.close")}><X size={17}/></button></div><div className="mt-4 space-y-2">{templates.map(item => <button key={item} type="button" onClick={() => { setTemplate(item); setTemplatesOpen(false); }} className="flex w-full items-center justify-between rounded-[11px] bg-white p-3 text-left text-[12px] font-semibold text-charcoal">{t(`imageStudio.template.${item}`)}<LayoutTemplate size={14} className="text-terracotta"/></button>)}</div></aside></div>}
  </div></main>;
}
