"use client";

import Link from "next/link";
import { legalDocuments } from "@/lib/legal/content";
import { useI18n } from "@/lib/i18n";

const legalLinks = ["terms", "privacy", "subscription", "refund", "cookies", "ai-disclaimer", "acceptable-use"];
const purposes = {
  uk: [["Створення та керування акаунтом", "Виконання договору"], ["Підключення та синхронізація Etsy", "Виконання договору / запитана послуга"], ["AI-відповіді та запитаний аналіз", "Виконання договору"], ["Білінг і підписка", "Виконання договору + юридичні обов’язки, якщо застосовні"], ["Запобігання шахрайству та безпека", "Законний інтерес"], ["Надійність і діагностика", "Законний інтерес"], ["Необов’язкові маркетингові повідомлення", "Згода, якщо потрібна"]],
  en: [["Create and manage the user account", "Performance of contract"], ["Connect and synchronize Etsy", "Performance of contract / user-requested service"], ["Generate AI responses and requested analysis", "Performance of contract"], ["Billing and subscription administration", "Performance of contract + legal obligations where applicable"], ["Fraud prevention and security", "Legitimate interests"], ["Service reliability and troubleshooting", "Legitimate interests"], ["Optional marketing communications", "Consent, where required"]],
} as const;

const complianceNotes = {
  uk: {
    minimization: ["Мінімізація даних", "Lucy прагне збирати та обробляти лише дані, обґрунтовано необхідні для надання запитаної функціональності, підтримки підключень, захисту сервісу, підтримки користувачів і виконання юридичних обов’язків. Незв’язані дані за замовчуванням не збираються."],
    retention: ["Строки зберігання", "Дані облікового запису зберігаються під час активності акаунта та обмежений період після цього, якщо це потрібно для юридичних, безпекових, спорів або бухгалтерських обов’язків. Підписні та бухгалтерські записи зберігаються відповідно до застосовного права. Історія чату зберігається, поки потрібна для історії акаунта, і до видалення користувачем або за визначеною політикою. OAuth-дані зберігаються, поки інтеграція підключена, та видаляються/інвалідуються після відключення з урахуванням журналів безпеки. Журнали безпеки зберігаються обмежений період, пропорційний потребам захисту. TODO: визначити операційні строки зберігання до запуску production."],
    security: ["Безпека та інциденти", "Ми застосовуємо обґрунтовані технічні й організаційні заходи, зокрема контроль доступу, шифрований транспорт, безпечну роботу з OAuth/токенами, обмежений доступ до production-систем, моніторинг, журналювання, керування секретами та автентифікацію. Lucy оцінює інциденти персональних даних і повідомляє компетентні органи та постраждалих осіб, коли цього вимагає застосовне право."],
    withdrawal: ["Цифрова послуга та право на відмову", "До негайної активації платної цифрової послуги для споживачів ЄС/ЄЕЗ checkout має отримати окреме явне підтвердження/згоду, якщо це потрібно для застосування правил про втрату права на відмову після початку виконання. TODO: узгодити точний withdrawal/consent flow з live payment і activation процесом."],
    actions: ["Автоматизовані дії", "Перед діями, що істотно змінюють дані Etsy, сервіс має чітко показати, що буде виконано, і запросити належне підтвердження для важливих дій. Lucy не повинна мовчки публікувати або видаляти контент без дозволу користувача. Якщо функція лише створює чернетку, це має бути зазначено точно."],
    changes: ["Зміни політик", "Про істотні зміни до Умов або Політики конфіденційності ми можемо повідомити через in-app notice, email або інший розумний спосіб, якщо цього вимагає право. Продовження використання не вважається згодою там, де закон вимагає окремої явної згоди."]
  },
  en: {
    minimization: ["Data minimisation", "Lucy aims to collect and process only data reasonably necessary to provide requested functionality, maintain account connections, secure the service, provide support, and comply with legal obligations. Unrelated data is not collected by default."],
    retention: ["Retention framework", "Account data is retained while the account is active and for a limited period afterward where needed for legal, security, dispute, or accounting obligations. Subscription and accounting records are retained as required by applicable law. Chat history is retained while needed for account history and until deleted by the user or under a defined policy. OAuth connection information is retained while connected and removed or invalidated when disconnected, subject to security-log needs. Security logs are retained for a limited period proportionate to security needs. TODO: define operational retention periods before production launch."],
    security: ["Security and incidents", "We use reasonable technical and organisational measures, including access controls, encrypted transport, secure OAuth/token handling, limited access to production systems, monitoring, logging, secret management, and account authentication. Lucy will assess personal-data breaches and notify competent authorities and affected individuals when required by applicable law."],
    withdrawal: ["Digital service and withdrawal", "Before immediate activation of a paid digital service for EU/EEA consumers, checkout must obtain separate explicit acknowledgement or consent where required to rely on rules concerning loss of a withdrawal right after performance begins. TODO: confirm the exact withdrawal/consent flow with the live payment and activation process."],
    actions: ["Automated actions", "Before actions that materially change Etsy data, the service should clearly identify what will happen and obtain appropriate confirmation for high-impact actions. Lucy must not silently publish or delete content without user authorisation. Where a feature only creates drafts, it must say so accurately."],
    changes: ["Policy changes", "Material changes to the Terms or Privacy Policy may be communicated through an in-app notice, email, or another reasonable method where required. Continued use is not treated as consent where separate explicit consent is legally required."]
  }
} as const;

export default function LegalClient({ slug }: { slug: string }) {
  const { locale } = useI18n();
  const document = legalDocuments[locale][slug] ?? legalDocuments[locale].terms;
  const localized = locale === "uk";
  const effective = localized ? "Чинна з: 28 серпня 2026" : "Effective: August 28, 2026";
  const version = localized ? "Версія 1.0" : "Version 1.0";
  return <main className="min-h-screen bg-[#F7F4F1] px-4 py-8 sm:px-6 lg:px-10"><div className="mx-auto max-w-[900px]">
    <div className="mb-6 flex items-center justify-between gap-4"><Link href="/" className="text-[11px] font-semibold text-terracotta">Lucy Seller Copilot</Link><Link href="/settings" className="text-[10px] font-semibold text-charcoal/55 hover:text-terracotta">{localized ? "До налаштувань" : "Back to settings"}</Link></div>
    <article className="rounded-[22px] border border-charcoal/[0.07] bg-white p-6 shadow-[0_18px_50px_rgba(51,51,51,0.04)] sm:p-10"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-terracotta">{localized ? "Юридична інформація" : "Legal information"}</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.05em] text-charcoal">{document.title}</h1><p className="mt-2 text-[10px] text-charcoal/40">{effective} · {document.updated} · {version}</p>
      <nav className="mt-6 flex flex-wrap gap-2 border-y border-charcoal/[0.07] py-4" aria-label="Legal pages">{legalLinks.map((link) => <Link key={link} href={`/legal/${link}`} className={`rounded-[9px] px-2.5 py-1.5 text-[10px] font-semibold ${link === slug ? "bg-terracotta/10 text-terracotta" : "text-charcoal/50 hover:bg-linen/30"}`}>{legalDocuments[locale][link]?.title}</Link>)}</nav>
      <section className="mt-6 rounded-[14px] bg-[#FCFAF8] p-4"><h2 className="text-[12px] font-semibold text-charcoal">{localized ? "Зміст" : "Contents"}</h2><div className="mt-2 grid gap-1 sm:grid-cols-2">{document.sections.map(([heading]) => <a key={heading} href={`#${heading}`} className="text-[10px] text-charcoal/50 hover:text-terracotta">{heading}</a>)}</div></section>
      <div className="mt-8 space-y-7">{document.sections.map(([heading, body]) => <section key={heading} id={heading} className="scroll-mt-6"><h2 className="text-[15px] font-semibold text-charcoal">{heading}</h2><p className="mt-2 text-[12px] leading-6 text-charcoal/65">{body}</p></section>)}
        {(slug === "privacy" || slug === "terms" || slug === "refund" || slug === "subscription") && <section><h2 className="text-[15px] font-semibold text-charcoal">{complianceNotes[locale].minimization[0]}</h2><p className="mt-2 text-[12px] leading-6 text-charcoal/65">{complianceNotes[locale].minimization[1]}</p></section>}
        {slug === "privacy" && <><section><h2 className="text-[15px] font-semibold text-charcoal">{complianceNotes[locale].retention[0]}</h2><p className="mt-2 text-[12px] leading-6 text-charcoal/65">{complianceNotes[locale].retention[1]}</p></section><section><h2 className="text-[15px] font-semibold text-charcoal">{complianceNotes[locale].security[0]}</h2><p className="mt-2 text-[12px] leading-6 text-charcoal/65">{complianceNotes[locale].security[1]}</p></section></>}
        {(slug === "terms" || slug === "refund") && <section><h2 className="text-[15px] font-semibold text-charcoal">{complianceNotes[locale].withdrawal[0]}</h2><p className="mt-2 text-[12px] leading-6 text-charcoal/65">{complianceNotes[locale].withdrawal[1]}</p></section>}
        {slug === "terms" && <><section><h2 className="text-[15px] font-semibold text-charcoal">{complianceNotes[locale].actions[0]}</h2><p className="mt-2 text-[12px] leading-6 text-charcoal/65">{complianceNotes[locale].actions[1]}</p></section><section><h2 className="text-[15px] font-semibold text-charcoal">{complianceNotes[locale].changes[0]}</h2><p className="mt-2 text-[12px] leading-6 text-charcoal/65">{complianceNotes[locale].changes[1]}</p></section></>}
        {slug === "privacy" && <section><h2 className="text-[15px] font-semibold text-charcoal">{localized ? "Цілі та правові підстави" : "Purposes and legal bases"}</h2><div className="mt-3 overflow-x-auto rounded-[12px] border border-charcoal/[0.07]"><table className="w-full min-w-[560px] border-collapse text-left"><thead><tr className="border-b border-charcoal/[0.07] bg-[#FCFAF8]"><th className="px-3 py-2 text-[9px] uppercase tracking-[0.08em] text-charcoal/40">{localized ? "Мета" : "Purpose"}</th><th className="px-3 py-2 text-[9px] uppercase tracking-[0.08em] text-charcoal/40">{localized ? "Правова підстава" : "Legal basis"}</th></tr></thead><tbody>{purposes[locale].map(([purpose, basis]) => <tr key={purpose} className="border-b border-charcoal/[0.06] last:border-0"><td className="px-3 py-2.5 text-[10px] text-charcoal/65">{purpose}</td><td className="px-3 py-2.5 text-[10px] text-charcoal/55">{basis}</td></tr>)}</tbody></table></div></section>}
      </div>
    </article>
    <footer className="mt-5 flex flex-wrap gap-x-4 gap-y-2 px-1 text-[10px] text-charcoal/45">{legalLinks.map((link) => <Link key={link} href={`/legal/${link}`} className="hover:text-terracotta">{legalDocuments[locale][link]?.title}</Link>)}</footer>
  </div></main>;
}
